# Generated by Django 3.2.4 on 2021-06-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0015_auto_20210429_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diff',
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=None,
        ),
        migrations.AlterIndexTogether(
            name='document',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='document',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Layer',
        ),
        migrations.AlterUniqueTogether(
            name='noticecfrpart',
            unique_together=None,
        ),
        migrations.AlterIndexTogether(
            name='noticecfrpart',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='noticecfrpart',
            name='notice',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='NoticeCFRPart',
        ),
    ]
