# Generated by Django 3.2.22 on 2023-10-10 14:05

import common.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0032_auto_20230912_1345'),
        ('file_manager', '0013_rename_subject_uploadedfile_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name_string', models.CharField(blank=True, max_length=512, null=True)),
                ('summary_string', models.TextField(blank=True, null=True)),
                ('file_name_string', models.CharField(blank=True, max_length=512, null=True)),
                ('date_string', common.fields.VariableDateField(blank=True, help_text='Leave blank or enter one of: "YYYY", "YYYY-MM", or "YYYY-MM-DD".', max_length=10, null=True, validators=[common.fields.validate_date, django.core.validators.RegexValidator(message='Date field must be blank or of the format "YYYY", "YYYY-MM", or "YYYY-MM-DD". For example: 2021, 2021-01, or 2021-01-31.', regex='^\\d{4}((-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]))|(-(0[1-9]|1[0-2])))?$')])),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=25, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to='resources.abstractcategory')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to='file_manager.documenttype')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_manager.uploadedfile')),
                ('fr_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.federalregisterdocument')),
                ('locations', models.ManyToManyField(blank=True, related_name='content', to='resources.AbstractLocation', verbose_name='Regulation Locations')),
                ('subjects', models.ManyToManyField(blank=True, related_name='content', to='file_manager.Subject')),
                ('supplemental_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.supplementalcontent')),
            ],
        ),
    ]
