# Generated by Django 3.2.22 on 2023-10-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_manager', '0011_auto_20230925_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name_string', models.CharField(blank=True, max_length=512, null=True)),
                ('summary_string', models.CharField(blank=True, max_length=512, null=True)),
                ('subject_string', models.CharField(blank=True, max_length=512, null=True)),
                ('file_name_string', models.CharField(blank=True, max_length=512, null=True)),
                ('doc_type_string', models.CharField(blank=True, max_length=512, null=True)),
                ('date_string', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager.uploadedfile')),
            ],
        ),
    ]
