# Generated by Django 3.2.22 on 2023-10-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentindex',
            name='file',
        ),
    ]
