# Generated by Django 5.0.7 on 2024-08-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0001_to_0012_squashed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentindex',
            options={'verbose_name': 'Content Index', 'verbose_name_plural': 'Content Indices'},
        ),
    ]
