# Generated by Django 5.0.4 on 2024-07-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0001_to_0012_squashed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentindex',
            options={'base_manager_name': 'objects', 'verbose_name': 'Content Index', 'verbose_name_plural': 'Content Indices'},
        ),
    ]
