# Generated by Django 3.2.22 on 2023-10-04 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0032_auto_20230912_1345'),
        ('file_manager', '0011_auto_20230925_1423'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('content_search', '0002_remove_contentindex_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindex',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to='file_manager.documenttype'),
        ),
        migrations.AddField(
            model_name='contentindex',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='content', to='resources.AbstractLocation', verbose_name='Regulation Locations'),
        ),
        migrations.AddField(
            model_name='contentindex',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='content', to='file_manager.Subject'),
        ),
        migrations.CreateModel(
            name='GenericContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
