# Generated by Django 3.2.22 on 2023-10-12 15:29

from django.db import migrations, models

from content_search.models import ContentIndex

def get_type(apps, schema_editor):
    cont_index = ContentIndex.objects.all()
    for ci in cont_index:
        if ci.file:
            ci.content_type = 'uploaded-file'
            ci.content_id = ci.file.id
        elif ci.supplemental_content:
            ci.content_type = 'supplemental-content'
            ci.content_id = ci.supplemental_content.id
        elif ci.fr_doc:
            ci.content_type = 'fr-doc'
            ci.content_id = ci.fr_doc.id
        ci.save()

class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0003_populate_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindex',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contentindex',
            name='content_id',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(get_type),
    ]
