# Generated by Django 3.2.23 on 2023-11-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0003_contentindex_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindex',
            name='rank_a_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentindex',
            name='rank_b_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentindex',
            name='rank_c_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentindex',
            name='rank_d_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
