# Generated by Django 5.1.6 on 2025-04-01 15:09

from django.db import migrations, models
from django.db.models import Q


def populate_date(apps, schema_editor):
    ContentIndex = apps.get_model('content_search', 'ContentIndex')
    for index in ContentIndex.objects.filter(Q(resource__isnull=False) & ~Q(resource__date="")):
        index.date = index.resource.date
        index.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0004_copy_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindex',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.RunPython(populate_date, reverse_code=migrations.RunPython.noop),
    ]
