# Generated by Django 3.2.22 on 2023-10-05 13:05

import common.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0004_auto_20231004_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentindex',
            name='doc_type_string',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='subject_string',
        ),
        migrations.AddField(
            model_name='contentindex',
            name='url',
            field=models.CharField(default='l', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentindex',
            name='date_string',
            field=common.fields.VariableDateField(blank=True, help_text='Leave blank or enter one of: "YYYY", "YYYY-MM", or "YYYY-MM-DD".', max_length=10, null=True, validators=[common.fields.validate_date, django.core.validators.RegexValidator(message='Date field must be blank or of the format "YYYY", "YYYY-MM", or "YYYY-MM-DD". For example: 2021, 2021-01, or 2021-01-31.', regex='^\\d{4}((-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]))|(-(0[1-9]|1[0-2])))?$')]),
        ),
    ]
