# Generated by Django 5.1.6 on 2025-04-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0004_copy_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindex',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
