# Generated by Django 3.2.23 on 2023-12-07 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0015_auto_20231207_0955'),
        ('content_search', '0005_populate_rank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindex',
            name='upload_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='file_manager.abstractrepocategory'),
        ),
    ]
