# Generated by Django 3.2.24 on 2024-03-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0017_auto_20240301_1210'),
        ('content_search', '0006_contentindex_upload_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindex',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_manager.division'),
        ),
    ]
