# Generated by Django 3.2.22 on 2023-10-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0032_auto_20230912_1345'),
        ('content_search', '0006_add_vector_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindex',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to='resources.abstractcategory'),
        ),
        migrations.AddField(
            model_name='contentindex',
            name='supplemental_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.supplementalcontent'),
        ),
    ]
