# Generated by Django 3.2.24 on 2024-03-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0007_contentindex_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindex',
            name='ignore_robots_txt',
            field=models.BooleanField(default=False),
        ),
    ]
