# Generated by Django 3.2.22 on 2023-10-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0007_auto_20231006_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentindex',
            old_name='subject',
            new_name='subjects',
        ),
    ]
