# Generated by Django 3.2.22 on 2023-10-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0008_rename_subject_contentindex_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindex',
            name='resource_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
