# Generated by Django 5.2.3 on 2025-07-23 16:57

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0008_contentindex_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentindex',
            name='embedding',
        ),
        migrations.CreateModel(
            name='TextEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, default=None, dimensions=512, null=True)),
                ('chunk_index', models.IntegerField()),
                ('start_offset', models.IntegerField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='content_search.contentindex')),
            ],
            options={
                'verbose_name': 'Text Embedding',
                'verbose_name_plural': 'Text Embeddings',
                'indexes': [models.Index(fields=['index'], name='content_sea_index_i_ce477b_idx'), models.Index(fields=['embedding'], name='content_sea_embeddi_fa4b7e_idx')],
                'unique_together': {('index', 'chunk_index')},
            },
        ),
    ]
