# Generated by Django 5.2.6 on 2025-09-24 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0008_contentindex_embedding'),
        ('resources', '0013_remove_internalfile_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentindex',
            name='reg_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='content_search.indexedregulationtext'),
        ),
        migrations.AlterField(
            model_name='contentindex',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='resources.abstractresource'),
        ),
    ]
