# Generated by Django 3.2.24 on 2024-03-07 15:14

from django.db import migrations, models


def populate_extract_url(apps, schema_editor):
    ContentIndex = apps.get_model("content_search", "ContentIndex")
    for i in ContentIndex.objects.all():
        i.extract_url = i.url
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0008_contentindex_ignore_robots_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindex',
            name='extract_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.RunPython(populate_extract_url),
    ]
