# Generated by Django 3.2.24 on 2024-03-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0009_contentindex_extract_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentindex',
            name='document_type',
        ),
    ]
