# Generated by Django 3.2.22 on 2023-10-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0009_contentindex_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentindex',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
