# Generated by Django 5.2.3 on 2025-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0009_remove_contentindex_embedding_textembedding'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textembedding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='textembedding',
            name='embedding_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='textembedding',
            unique_together={('index', 'chunk_index', 'embedding_type')},
        ),
    ]
