# Generated by Django 5.0.4 on 2024-05-30 17:22

import django.db.models.deletion
from django.db import migrations, models


def migrate_resources(apps, schema_editor):
    ContentIndex = apps.get_model("content_search", "ContentIndex")
    AbstractPublicResource = apps.get_model("resources", "AbstractPublicResource")
    AbstractInternalResource = apps.get_model("resources", "AbstractInternalResource")
    for i in ContentIndex.objects.all():
        if i.file:
            i.resource = AbstractInternalResource.objects.get(old_pk=i.file.pk)
        elif i.fr_doc or i.supplemental_content:
            old_resource = i.fr_doc or i.supplemental_content
            i.resource = AbstractPublicResource.objects.get(old_pk=old_resource.pk)
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0010_remove_contentindex_document_type'),
        ('resources', '0036_alter_resourcegroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindex',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.newabstractresource'),
        ),
        migrations.RunPython(migrate_resources),
        migrations.RemoveField(
            model_name='contentindex',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='division',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='file',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='fr_doc',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='supplemental_content',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='upload_category',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='locations',
        ),
    ]
