# Generated by Django 5.2.6 on 2025-09-24 14:22

import django.core.validators
import django_jsonform.models.fields
import django.db.models.deletion
from django.db import migrations, models


def create_content_search_configuration(apps, schema_editor):
    ContentSearchConfiguration = apps.get_model('content_search', 'ContentSearchConfiguration')
    if apps.is_installed("resources"):
        ResourcesConfiguration = apps.get_model('resources', 'ResourcesConfiguration')
        resources_config = ResourcesConfiguration.objects.first()
        if resources_config:
            ContentSearchConfiguration.objects.create(
                auto_extract=resources_config.auto_extract,
                extraction_delay_time=resources_config.extraction_delay_time,
                robots_txt_allow_list=resources_config.robots_txt_allow_list,
                user_agent_override_list=resources_config.user_agent_override_list,
                default_user_agent_override=resources_config.default_user_agent_override,
            )
    else:
        ContentSearchConfiguration.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0010_remove_empty_subpart_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentindex',
            name='reg_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='content_search.indexedregulationtext'),
        ),
        migrations.AlterField(
            model_name='contentindex',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='resources.abstractresource'),
        ),
        migrations.CreateModel(
            name='ContentSearchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_extract', models.BooleanField(default=False, help_text='Check this box if eRegs should automatically request text extraction on any resource when it is originally saved/created or when its source is changed: URL (for public and internal links), document number (for FR links), or attached file (for internal files).', verbose_name='Auto Extract')),
                ('extraction_delay_time', models.IntegerField(blank=True, default=180, help_text='The number of seconds to delay between multiple text extraction requests. This is useful to prevent overloading external services with too many requests in a short period of time.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Extraction Delay Time')),
                ('robots_txt_allow_list', django_jsonform.models.fields.JSONField(blank=True, default=list, help_text="A list of URLs and/or domains that the text extractor should be allowed to access, even if eRegs is not in their robots.txt file. For example, 'example.com' will allow the entire domain and all subdomains to be accessed, while 'https://example.com/page.html' will allow only that specific page.", verbose_name='Robots.txt Allow List')),
                ('user_agent_override_list', django_jsonform.models.fields.JSONField(blank=True, default=list, help_text="A list of domains and user agents that the text extractor should use instead of the default user agent. This is useful for sites that block eRegs' default user agent. Note that a domain will match all subdomains.", verbose_name='User Agent Override List')),
                ('default_user_agent_override', models.CharField(blank=True, default='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:140.0) Gecko/20100101 Firefox/140.0', help_text="A default user agent to use for all requests to domains in the user agent override list that do not specify a user agent. This is useful for sites that block eRegs' default user agent.", max_length=255, verbose_name='Default User Agent Override')),
            ],
            options={
                'verbose_name': 'Content Search Configuration',
            },
        ),
        migrations.RunPython(create_content_search_configuration, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='ResourceMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_file_type', models.CharField(blank=True, editable=False, help_text='The file type that the text extractor detected for this resource.', max_length=32)),
                ('extraction_error', models.TextField(blank=True, editable=False, help_text='If the text extractor failed to extract text from this resource, the error message will be stored here.')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='index_metadata', to='resources.abstractresource')),
                ('date', models.CharField(max_length=10, null=True)),
                ('name', models.TextField(blank=True)),
                ('rank_a_string', models.TextField(blank=True)),
                ('rank_b_string', models.TextField(blank=True)),
                ('rank_c_string', models.TextField(blank=True)),
                ('rank_d_string', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='contentindex',
            name='resource_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='content_search.resourcemetadata'),
        ),
        migrations.AddField(
            model_name='contentindex',
            name='chunk_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name='contentindex',
            options={'ordering': ('resource', 'reg_text', 'chunk_index'), 'verbose_name': 'Content Index', 'verbose_name_plural': 'Content Indices'},
        ),
        migrations.AlterUniqueTogether(
            name='contentindex',
            unique_together={('reg_text', 'chunk_index'), ('resource', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='contentindex',
            index=models.Index(fields=['-date'], name='content_sea_date_0c54a7_idx'),
        ),
        migrations.AddIndex(
            model_name='contentindex',
            index=models.Index(fields=['resource'], name='content_sea_resourc_76375a_idx'),
        ),
        migrations.AddIndex(
            model_name='contentindex',
            index=models.Index(fields=['reg_text'], name='content_sea_reg_tex_a76755_idx'),
        ),
        migrations.AddIndex(
            model_name='contentindex',
            index=models.Index(fields=['chunk_index'], name='content_sea_chunk_i_190500_idx'),
        ),
        migrations.AddIndex(
            model_name='contentindex',
            index=models.Index(fields=['embedding'], name='content_sea_embeddi_3aff99_idx'),
        ),
        migrations.DeleteModel(
            name='Synonym',
        ),
    ]
