# Generated by Django 5.0.4 on 2024-05-30 17:22

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Case, When, OuterRef, Subquery


TIMEOUT_MINUTES = 10


def migrate_resources(apps, schema_editor):
    schema_editor.execute(f"SET LOCAL statement_timeout TO {TIMEOUT_MINUTES * 60000};")
    ContentIndex = apps.get_model("content_search", "ContentIndex")
    AbstractPublicResource = apps.get_model("resources", "AbstractPublicResource")
    AbstractInternalResource = apps.get_model("resources", "AbstractInternalResource")
    ContentIndex.objects.update(resource=Case(
        When(file__isnull=False, then=Subquery(AbstractInternalResource.objects.filter(old_pk=OuterRef("file__pk")).values("pk"))),
        When(fr_doc__isnull=False, then=Subquery(AbstractPublicResource.objects.filter(old_pk=OuterRef("fr_doc__pk")).values("pk"))),
        When(supplemental_content__isnull=False, then=Subquery(AbstractPublicResource.objects.filter(old_pk=OuterRef("supplemental_content__pk")).values("pk"))),
        default=None,
    ))


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0010_remove_contentindex_document_type'),
        ('resources', '0036_alter_resourcegroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindex',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.newabstractresource'),
        ),
        migrations.RunPython(migrate_resources),
        migrations.RemoveField(
            model_name='contentindex',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='division',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='file',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='fr_doc',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='supplemental_content',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='upload_category',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='locations',
        ),
    ]
