# Generated by Django 5.0.4 on 2024-06-13 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0011_remove_v3_dependencies'),
        ('regcore', '0014_auto_20230322_2234'),
        ('resources', '0040_rename_v4_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentindex',
            name='date_string',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='doc_name_string',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='extract_url',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='file_name_string',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='ignore_robots_txt',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='summary_string',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='contentindex',
            name='url',
        ),
        migrations.AddField(
            model_name='contentindex',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentindex',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentindex',
            name='content',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentindex',
            name='rank_a_string',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentindex',
            name='rank_b_string',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentindex',
            name='rank_c_string',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentindex',
            name='rank_d_string',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentindex',
            name='resource',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index', to='resources.abstractresource'),
        ),
        migrations.CreateModel(
            name='IndexedRegulationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regcore.part')),
            ],
        ),
        migrations.AddField(
            model_name='contentindex',
            name='reg_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index', to='content_search.indexedregulationtext'),
        ),
    ]
