# Generated by Django 5.2.8 on 2025-11-17 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0012_create_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='enable_keyword_search',
            field=models.BooleanField(default=True, help_text='Enable traditional keyword-based search for precise matching of search terms.', verbose_name='Enable Keyword Search'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='enable_semantic_search',
            field=models.BooleanField(default=True, help_text='Enable semantic search using vector embeddings for more relevant search results.', verbose_name='Enable Semantic Search'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='generate_embeddings',
            field=models.BooleanField(default=True, help_text='Generate vector embeddings during text extraction to enable semantic search.', verbose_name='Generate Embeddings'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='headline_max_fragments',
            field=models.IntegerField(default=2, help_text='Maximum number of headline fragments to generate. Set to 0 for no limit.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Headline Maximum Fragments'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='headline_max_words',
            field=models.IntegerField(default=50, help_text='Maximum number of words in each headline fragment.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Headline Maximum Words'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='headline_min_words',
            field=models.IntegerField(default=30, help_text='Minimum number of words in each headline fragment.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Headline Minimum Words'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='headline_text_max_length',
            field=models.IntegerField(default=150000, help_text='Maximum length of text to consider when generating search result headlines.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Headline Text Maximum Length'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='keyword_search_max_words',
            field=models.IntegerField(default=15, help_text='Maximum number of words allowed in the search query to enable keyword search if semantic search is enabled.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Keyword Search Maximum Words'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='keyword_search_min_rank',
            field=models.FloatField(default=0.05, help_text='Minimum rank threshold for keyword search results to be included.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Keyword Search Minimum Rank'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='keyword_search_min_rank_quoted',
            field=models.FloatField(default=0.05, help_text='Minimum rank threshold for keyword search results to be included when the query is quoted.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Keyword Search Minimum Rank for Quoted Queries'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='rrf_k_value',
            field=models.IntegerField(default=60, help_text="The 'k' value used in the Reciprocal Rank Fusion (RRF) algorithm to combine keyword and semantic search results.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='RRF K Value'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='semantic_search_max_distance',
            field=models.FloatField(default=0.5, help_text='Maximum distance threshold for semantic search results to be included.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Semantic Search Maximum Distance'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='semantic_search_min_words',
            field=models.IntegerField(default=2, help_text='Minimum number of words required in the search query to allow semantic search if keyword search is enabled.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semantic Search Minimum Words'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='use_keyword_search_for_quoted',
            field=models.BooleanField(default=True, help_text='Use keyword search for quoted search queries to ensure exact phrase matching.', verbose_name='Use Keyword Search for Quoted Queries'),
        ),
    ]
