# Generated by Django 5.2.7 on 2025-11-26 10:49

from django.db import migrations, models

TIMEOUT_MINUTES = 15


def populate_name_and_summary(apps, schema_editor):
    IndexedRegulationText = apps.get_model('content_search', 'IndexedRegulationText')
    ContentIndex = apps.get_model('content_search', 'ContentIndex')

    for indexed_text in IndexedRegulationText.objects.all():
        try:
            index = indexed_text.indices.first()
            indexed_text.name = index.name
            indexed_text.summary = index.summary
            indexed_text.save()
        except ContentIndex.DoesNotExist:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0013_contentsearchconfiguration_enable_keyword_search_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=f"SET statement_timeout = '{TIMEOUT_MINUTES}min';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='indexedregulationtext',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indexedregulationtext',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(populate_name_and_summary),
    ]
