# Generated by Django 5.2.7 on 2025-12-09 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0014_indexedregulationtext_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='semantic_distance_algorithm',
            field=models.CharField(choices=[('<=>', 'Cosine Distance'), ('<->', 'L2 Distance'), ('<+>', 'L1 Distance'), ('<#>', 'Inner Product')], default='<=>', help_text='The distance algorithm to use for semantic search comparisons. Note that your choice here will affect the interpretation of the maximum distance threshold.', max_length=16, verbose_name='Semantic Distance Algorithm'),
        ),
        migrations.AlterField(
            model_name='contentsearchconfiguration',
            name='keyword_search_max_words',
            field=models.IntegerField(default=15, help_text='Maximum number of words in a query where keyword search will be allowed. Queries exceeding this limit will use semantic search only, if enabled.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Keyword Search Maximum Words'),
        ),
        migrations.AlterField(
            model_name='contentsearchconfiguration',
            name='semantic_search_min_words',
            field=models.IntegerField(default=2, help_text='Minimum number of words in a query where semantic search will be allowed. Queries with fewer words will use keyword search only, if enabled.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semantic Search Minimum Words'),
        ),
    ]
