# Generated by Django 5.2.7 on 2025-12-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0015_contentsearchconfiguration_semantic_distance_algorithm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsearchconfiguration',
            name='semantic_distance_algorithm',
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='semantic_search_distance_algorithm',
            field=models.CharField(choices=[('<=>', 'Cosine Distance'), ('<->', 'L2 Distance'), ('<+>', 'L1 Distance'), ('<#>', 'Inner Product')], default='<=>', help_text='The distance algorithm to use for semantic search comparisons. Note that your choice here will affect the interpretation of the maximum distance threshold.', max_length=16, verbose_name='Semantic Search Distance Algorithm'),
        ),
    ]
