# Generated by Django 5.2.7 on 2025-12-10 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0016_remove_contentsearchconfiguration_semantic_distance_algorithm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsearchconfiguration',
            name='semantic_search_max_distance',
            field=models.FloatField(default=0.5, help_text='Maximum distance threshold for semantic search results to be included.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Semantic Search Maximum Distance'),
        ),
    ]
