# Generated by Django 5.2.7 on 2025-12-16 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0017_alter_contentsearchconfiguration_semantic_search_max_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='default_page_size',
            field=models.IntegerField(default=50, help_text='The default number of search results to return per page if the client does not specify a page size.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Default Page Size'),
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='query_text_max_length',
            field=models.IntegerField(default=0, help_text='Maximum length of query text to consider when generating search result headlines. Set to 0 for no limit.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Query Text Maximum Length'),
        ),
        migrations.AlterField(
            model_name='contentsearchconfiguration',
            name='headline_text_max_length',
            field=models.IntegerField(default=0, help_text='Maximum length of document text to consider when generating search result headlines. Set to 0 for no limit.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Headline Text Maximum Length'),
        ),
    ]
