# Generated by Django 5.2.7 on 2025-12-17 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0018_contentsearchconfiguration_default_page_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsearchconfiguration',
            name='query_text_max_length',
        ),
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='query_text_max_words',
            field=models.IntegerField(default=0, help_text='Maximum number of words of query text to consider when generating search result headlines. Set to 0 for no limit.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Query Text Maximum Words'),
        ),
    ]
