# Generated by Django 5.2.9 on 2026-01-09 13:17

from django.db import migrations


def reset_config_defaults(apps, schema_editor):
    ContentSearchConfiguration = apps.get_model('content_search', 'ContentSearchConfiguration')

    default_values = {
        "default_page_size": 25,
        "keyword_search_min_rank_quoted": 0.01,
        "semantic_search_max_distance": 0.6,
        "query_text_max_words": 50,
        "headline_min_words": 40,
        "headline_max_fragments": 3,
        "extraction_delay_time": 30,
    }

    config = ContentSearchConfiguration.objects.first()
    if config:
        for field, default in default_values.items():
            setattr(config, field, default)
        config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0019_remove_contentsearchconfiguration_query_text_max_length_and_more'),
    ]

    operations = [
        migrations.RunPython(reset_config_defaults, reverse_code=migrations.RunPython.noop),
    ]
