# Generated by Django 5.2.9 on 2026-01-27 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0020_reset_config_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsearchconfiguration',
            name='database_timeout',
            field=models.IntegerField(default=10, help_text='The maximum number of seconds to wait for the database to respond to search queries.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Database Timeout'),
        ),
    ]
