title = "Gitleaks Configuration"

[extend]
useDefault = true

[allowlist]
description = "global allow list"
paths = [
    "solution/text-extractor/extractors/tests/fixtures",
    "solution/text-extractor/README.md",
    "solution/text-extractor/test_utils.py"
]

