version: '3'
services:
    parser:
        image: golang:1.16
        container_name: parser
        network_mode: host
        environment:
        - USE_ENVIRONMENT_VARS=true
        - EREGS_USERNAME=${EREGS_USERNAME:-}
        - EREGS_PASSWORD=${EREGS_PASSWORD:-}
        - TITLE=${TITLE:-}
        - SUBCHAPTER=${SUBCHAPTER:-}
        - PARTS=${PARTS:-}
        - EREGS_URL=${EREGS_URL:-}
        - WORKERS=${WORKERS:-}
        - ATTEMPTS=${ATTEMPTS:-}
        - LOGLEVEL=${LOGLEVEL:-}
        - LOG_PARSE_ERRORS=${LOG_PARSE_ERRORS:-}
        - EREGS_SUPPLEMENTAL_URL=${EREGS_SUPPLEMENTAL_URL:-}
        - SKIP_EXISTING_VERSIONS=${SKIP_EXISTING_VERSIONS:-}
        working_dir: /app
        command: go run .
        volumes:
        - ./tools/ecfr-parser:/app
