version: '3'
services:
    e2e:
        image: cypress/included:7.0.1
        container_name: cypress
        network_mode: host
        depends_on:
        - regulations
        environment:
        - CYPRESS_baseUrl=http://localhost:8000
        working_dir: /app
        command: npx cypress run
        volumes:
        - ./e2e:/app
