language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install coveralls tox-travis
script:
  - tox
after_success:
  - if [[ $INTEGRATION_TARGET = '' ]] && [[ $TRAVIS_PYTHON_VERSION = '3.6' ]]; then coveralls; fi
