# Generated by Django 3.2.7 on 2021-10-06 17:39

from django.db import migrations


def migrate_supplemental_content_app(apps, schema_editor):
    # RunPython code removed after resources app squash
    pass


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(migrate_supplemental_content_app),
    ]
