# Generated by Django 3.2.12 on 2022-05-06 13:00

from django.db import migrations


def migrate_supplemental_content_app(apps, schema_editor):
    # RunPython code removed after resources app squash
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_supplemental_content_app),
    ]
