# Generated by Django 3.2.13 on 2022-06-21 14:36

from django.db import migrations, models


def create_default_site_config(apps, schema_editor):
    SiteConfiguration = apps.get_model("regulations", "SiteConfiguration")
    if len(SiteConfiguration.objects.all()) < 1:
        SiteConfiguration.objects.create()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regulations', '0002_rename_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_indexing', models.BooleanField(default=False, help_text='Should robots be allowed to index this website?')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.RunPython(create_default_site_config),
    ]
