# Generated by Django 3.2.18 on 2023-04-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0003_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatuteLinkConverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=128, verbose_name="Act Section")),
                ('title', models.IntegerField(verbose_name="USC Title")),
                ('usc', models.CharField(max_length=128, verbose_name="USC Section")),
                ('act', models.CharField(max_length=128, verbose_name="Act Name")),
                ('source_url', models.CharField(max_length=512, blank=True, null=True, verbose_name="Source URL")),
            ],
            options={
                'verbose_name': 'Statute Link Converter',
                'verbose_name_plural': 'Statute Link Converters',
            },
        ),
    ]
