# Generated by Django 3.2.18 on 2023-04-17 16:45

from django.db import migrations, models


def full_act_name(apps, schema_editor):
    StatuteLinkConverter = apps.get_model("regulations", "StatuteLinkConverter")
    for i in StatuteLinkConverter.objects.all():
        if i.act == "SSA":
            i.act = "Social Security Act"
        elif i.act == "ACA":
            i.act = "Affordable Care Act"
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0004_statutelinkconverter'),
    ]

    operations = [
        migrations.RunPython(full_act_name),
    ]
