# Generated by Django 3.2.19 on 2023-07-07 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0006_statutelinkconverter_statute_title_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
