# Generated by Django 3.2.18 on 2023-07-18 13:56

import re

from django.db import migrations

import common.fields


def naturalize(string):
    def naturalize_int_match(match):
        return '%08d' % (int(match.group(0)),)
    if string:
        string = string.lower()
        string = string.strip()
        string = re.sub(r'\d+', naturalize_int_match, string)
        string = string[:50]

    return string

def add_usc_sort(apps, schema_editor):
    StatuteLinkConverter = apps.get_model("regulations", "StatuteLinkConverter")
    for conv in StatuteLinkConverter.objects.all():
        conv.usc_sort = naturalize(conv.usc)
        conv.save()


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0006_statutelinkconverter_statute_title_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutelinkconverter',
            name='usc_sort',
            field=common.fields.NaturalSortField('usc', db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.RunPython(add_usc_sort),
    ]
