# Generated by Django 3.2.19 on 2023-07-10 17:34

from django.db import migrations, models
import django.utils.timezone
import partial_date.fields
import regulations.models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0007_siteconfiguration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='date_type',
            field=models.CharField(choices=[('effective', 'Effective'), ('amended', 'Amended')], default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='date',
            field=partial_date.fields.PartialDateField(blank=True, default=django.utils.timezone.now, null=True, validators=[regulations.models.validate_partial_date]),
        ),
    ]
