# Generated by Django 3.2.19 on 2023-07-19 11:57

import common.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0007_auto_20230714_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='date',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='date_type',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ssa_gov_compilation_date',
            field=common.fields.VariableDateField(blank=True, help_text='Leave blank or enter one of: "YYYY", "YYYY-MM", or "YYYY-MM-DD".', max_length=10, null=True, validators=[common.fields.validate_date, django.core.validators.RegexValidator(message='Date field must be blank or of the format "YYYY", "YYYY-MM", or "YYYY-MM-DD". For example: 2021, 2021-01, or 2021-01-31.', regex='^\\d{4}((-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]))|(-(0[1-9]|1[0-2])))?$')], verbose_name='SSA.gov Compilation Date'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ssa_gov_compilation_date_type',
            field=models.CharField(blank=True, choices=[('effective', 'Effective'), ('amended', 'Amended')], default='', max_length=10, null=True, verbose_name='SSA.gov Compilation Date Type'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='statute_compilation_date',
            field=common.fields.VariableDateField(blank=True, help_text='Leave blank or enter one of: "YYYY", "YYYY-MM", or "YYYY-MM-DD".', max_length=10, null=True, validators=[common.fields.validate_date, django.core.validators.RegexValidator(message='Date field must be blank or of the format "YYYY", "YYYY-MM", or "YYYY-MM-DD". For example: 2021, 2021-01, or 2021-01-31.', regex='^\\d{4}((-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]))|(-(0[1-9]|1[0-2])))?$')], verbose_name='Statute Compilation Date'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='statute_compilation_date_type',
            field=models.CharField(blank=True, choices=[('effective', 'Effective'), ('amended', 'Amended')], default='', max_length=10, null=True, verbose_name='Statute Compilation Date Type'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='us_code_annual_date',
            field=common.fields.VariableDateField(blank=True, help_text='Leave blank or enter one of: "YYYY", "YYYY-MM", or "YYYY-MM-DD".', max_length=10, null=True, validators=[common.fields.validate_date, django.core.validators.RegexValidator(message='Date field must be blank or of the format "YYYY", "YYYY-MM", or "YYYY-MM-DD". For example: 2021, 2021-01, or 2021-01-31.', regex='^\\d{4}((-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]))|(-(0[1-9]|1[0-2])))?$')], verbose_name='US Code Annual Date'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='us_code_annual_date_type',
            field=models.CharField(blank=True, choices=[('effective', 'Effective'), ('amended', 'Amended')], default='', max_length=10, null=True, verbose_name='US Code Annual Date Type'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='us_code_house_gov_date',
            field=common.fields.VariableDateField(blank=True, help_text='Leave blank or enter one of: "YYYY", "YYYY-MM", or "YYYY-MM-DD".', max_length=10, null=True, validators=[common.fields.validate_date, django.core.validators.RegexValidator(message='Date field must be blank or of the format "YYYY", "YYYY-MM", or "YYYY-MM-DD". For example: 2021, 2021-01, or 2021-01-31.', regex='^\\d{4}((-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]))|(-(0[1-9]|1[0-2])))?$')], verbose_name='US Code House.gov Date'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='us_code_house_gov_date_type',
            field=models.CharField(blank=True, choices=[('effective', 'Effective'), ('amended', 'Amended')], default='', max_length=10, null=True, verbose_name='US Code House.gov Date Type'),
        ),
    ]
