# Generated by Django 3.2.19 on 2023-07-10 18:39

from django.db import migrations
import partial_date.fields
import regulations.models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0008_auto_20230710_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='date',
            field=partial_date.fields.PartialDateField(blank=True, null=True, validators=[regulations.models.validate_partial_date]),
        ),
    ]
