# Generated by Django 3.2.18 on 2023-07-20 12:04

from django.db import migrations


def create_statute_link_config(apps, schema_editor):
    StatuteLinkConfiguration = apps.get_model("regulations", "StatuteLinkConfiguration")
    config = StatuteLinkConfiguration.objects.get_or_create()[0]
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0010_auto_20230719_1157'),
    ]

    operations = [
        migrations.RunPython(create_statute_link_config),
    ]
