# Generated by Django 3.2.18 on 2023-07-25 16:30

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0011_create_statutelinkconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statutelinkconfiguration',
            name='do_not_link',
        ),
        migrations.AddField(
            model_name='statutelinkconfiguration',
            name='statute_ref_exceptions',
            field=django_jsonform.models.fields.JSONField(blank=True, default=list, help_text='Statute references that are listed here will not be automatically linked.', verbose_name='Statute Ref Exceptions'),
        ),
        migrations.AddField(
            model_name='statutelinkconfiguration',
            name='usc_ref_exceptions',
            field=django_jsonform.models.fields.JSONField(blank=True, default=list, help_text='U.S.C. references that are listed here will not be automatically linked.', verbose_name='U.S.C. Ref Exceptions'),
        ),
        migrations.AlterField(
            model_name='statutelinkconfiguration',
            name='link_statute_refs',
            field=models.BooleanField(default=True, help_text='Should eRegs link statutes of the form "Section 1902 of the Act" to house.gov?', verbose_name='Link Statute Refs'),
        ),
        migrations.AlterField(
            model_name='statutelinkconfiguration',
            name='link_usc_refs',
            field=models.BooleanField(default=True, help_text='Should eRegs link statutes of the form "42 U.S.C. 123(a)" to house.gov?', verbose_name='Link U.S.C. Refs'),
        ),
    ]
