# Generated by Django 3.2.20 on 2023-08-17 14:54

from django.db import migrations, models
import django_jsonform.models.fields


def create_reg_link_config(apps, schema_editor):
    RegulationLinkConfiguration = apps.get_model("regulations", "RegulationLinkConfiguration")
    config = RegulationLinkConfiguration.objects.get_or_create()[0]
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0012_auto_20230725_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationLinkConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_ecfr', models.BooleanField(default=True, help_text='If a regulation does not exist in eRegs, should links redirect to eCFR?', verbose_name='Link to eCFR')),
                ('link_cfr_refs', models.BooleanField(default=True, help_text='Should eRegs link references of the form "42 CFR part 123"?', verbose_name='Link CFR Refs')),
                ('cfr_ref_exceptions', django_jsonform.models.fields.JSONField(blank=True, default=list, help_text='CFR-type references that are listed here will not be automatically linked.', verbose_name='CFR Ref Exceptions')),
            ],
            options={
                'verbose_name': 'Regulation Link Configuration',
            },
        ),
        migrations.RunPython(create_reg_link_config),
    ]
