# Generated by Django 3.2.20 on 2023-09-12 12:11

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0013_regulationlinkconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulationlinkconfiguration',
            name='cfr_ref_exceptions',
            field=common.fields.CfrRefField(blank=True, default=list, help_text='CFR-type references that are listed here will not be automatically linked.', verbose_name='CFR Ref Exceptions'),
        ),
        migrations.AlterField(
            model_name='statutelinkconfiguration',
            name='statute_ref_exceptions',
            field=common.fields.StatuteRefField(blank=True, default=list, help_text='Statute references that are listed here will not be automatically linked.', verbose_name='Statute Ref Exceptions'),
        ),
        migrations.AlterField(
            model_name='statutelinkconfiguration',
            name='usc_ref_exceptions',
            field=common.fields.UscRefField(blank=True, default=list, help_text='U.S.C. references that are listed here will not be automatically linked.', verbose_name='U.S.C. Ref Exceptions'),
        ),
    ]
