# Generated by Django 5.2.6 on 2025-10-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0017_alter_siteconfiguration_ssa_gov_compilation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='flash_banner_text',
            field=models.TextField(blank=True, help_text='The text to display in the flash banner.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_flash_banner',
            field=models.BooleanField(default=False, help_text='Should a flash banner be displayed at the top of every page?'),
        ),
    ]
