# Generated by Django 5.2.5 on 2025-10-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0018_siteconfiguration_flash_banner_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_title',
            field=models.IntegerField(default=42, help_text='The default title to use for dropdowns, selects, and tabs throughout the site.'),
        ),
    ]
