# Generated by Django 5.2.7 on 2025-11-20 14:29

import re

import common.fields
from django.db import migrations


def naturalize(string):
    def naturalize_int_match(match):
        return '%08d' % (int(match.group(0)),)
    if string:
        string = string.lower()
        string = string.strip()
        string = re.sub(r'\d+', naturalize_int_match, string)
        string = string[:50]

    return string

def add_section_sort(apps, schema_editor):
    StatuteLinkConverter = apps.get_model("regulations", "StatuteLinkConverter")
    for conv in StatuteLinkConverter.objects.all():
        conv.section_sort = naturalize(conv.section)
        conv.save()


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0019_siteconfiguration_default_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutelinkconverter',
            name='section_sort',
            field=common.fields.NaturalSortField('section', db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.RunPython(add_section_sort),
    ]
