# Generated by Django 5.2.6 on 2025-10-30 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0019_siteconfiguration_default_title'),
        ('resources', '0013_remove_internalfile_file_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionContextBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_html', models.TextField(blank=True, help_text='Optional HTML allowed. Keep it brief.', verbose_name='Banner HTML')),
                ('is_active', models.BooleanField(default=True)),
                ('citation', models.ForeignKey(help_text='Select a Section or Subpart to attach this banner to.', on_delete=django.db.models.deletion.CASCADE, related_name='context_banners', to='resources.abstractcitation')),
            ],
            options={
                'verbose_name': 'Context Banner',
                'verbose_name_plural': 'Context Banners',
            },
        ),
    ]
