# Generated by Django 5.2.7 on 2025-11-18 16:07

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0019_siteconfiguration_default_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutelinkconverter',
            name='section_sort',
            field=common.fields.NaturalSortGeminiField(null=True),
        ),
        migrations.AddField(
            model_name='statutelinkconverter',
            name='section_sort_key',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='statutelinkconverter',
            name='usc_sort_key',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statutelinkconverter',
            name='usc_sort',
            field=common.fields.NaturalSortGeminiField(null=True),
        ),
    ]
