version: '3'
services:
    parser:
        image: golang:1.16
        container_name: parser
        network_mode: host
        environment:
        - EREGS_USERNAME=${EREGS_USERNAME:-}
        - EREGS_PASSWORD=${EREGS_PASSWORD:-}
        - EREGS_API_URL_V3=${EREGS_API_URL_V3:-}
        working_dir: /app/ecfr-parser
        command: go run .
        volumes:
        - ./parser:/app

