# Generated by Django 3.2.6 on 2021-08-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplemental_content', '0002_auto_20210712_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='supplementarycontent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplementary_content', to='supplemental_content.category'),
        ),
        migrations.AlterField(
            model_name='supplementarycontent',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='supplementarycontent',
            name='url',
            field=models.URLField(max_length=512, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='regulationsection',
            unique_together={('title', 'part', 'section')},
        ),
    ]
