# Generated by Django 3.2.5 on 2021-08-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_content', '0005_auto_20210826_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulationsection',
            name='supplementary_content',
            field=models.ManyToManyField(blank=True, related_name='sections', to='supplementary_content.SupplementaryContent'),
        ),
    ]
