# Generated by Django 3.2.7 on 2021-10-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplemental_content', '0009_alter_abstractsupplementalcontent_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractsupplementalcontent',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='supplemental_content', to='supplemental_content.AbstractLocation'),
        ),
    ]
