# Generated by Django 3.2.6 on 2021-08-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_content', '0003_auto_20210820_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementarycontent',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
