# Generated by Django 3.2.5 on 2021-08-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_content', '0005_auto_20210825_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
