# Generated by Django 3.2.5 on 2021-08-31 16:12

from django.db import migrations, models


def split_dates(apps, schema_editor):
    SupplementaryContent = apps.get_model("supplementary_content", "SupplementaryContent")
    for content in SupplementaryContent.objects.all():
        if content.date is not None:
            content.year = content.date.year
            content.month = content.date.month
            content.day = content.date.day
        content.save()


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_content', '0006_alter_regulationsection_supplementary_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementarycontent',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplementarycontent',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplementarycontent',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(split_dates),
        migrations.RemoveField(
            model_name='supplementarycontent',
            name='date',
        ),
    ]
