# Generated by Django 3.2.7 on 2021-10-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_content', '0007_auto_20210831_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
                ('part', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplementalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='supplementarycontent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='show_if_empty',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supplementary_content.location')),
                ('section_id', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='supplementary_content.location')),
            ],
            bases=('supplementary_content.location',),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supplementary_content.category')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='supplementary_content.category')),
            ],
            bases=('supplementary_content.category',),
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supplementary_content.location')),
                ('subject_group_id', models.TextField()),
            ],
            bases=('supplementary_content.location',),
        ),
        migrations.CreateModel(
            name='Subpart',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supplementary_content.location')),
                ('subpart_id', models.CharField(max_length=12)),
            ],
            bases=('supplementary_content.location',),
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='supplementary_content.category')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sub_categories', to='supplementary_content.category')),
            ],
            bases=('supplementary_content.category',),
        ),
        migrations.DeleteModel(
            name='RegulationSection',
        ),
        migrations.DeleteModel(
            name='SupplementaryContent',
        ),
        migrations.AddField(
            model_name='supplementalcontent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplemental_content', to='supplementary_content.category'),
        ),
        migrations.AddField(
            model_name='supplementalcontent',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, related_name='supplemental_content', to='supplementary_content.Location'),
        ),
    ]
