# Generated by Django 3.2.5 on 2021-08-31 16:13

from django.db import migrations

def split_dates(apps, schema_editor):
    SupplementaryContent = apps.get_model("supplementary_content", "SupplementaryContent")
    for content in SupplementaryContent.objects.all():
        if content.date is not None:
            content.year = content.date.year
            content.month = content.date.month
            content.day = content.date.day
        content.save()


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_content', '0007_auto_20210831_1612'),
    ]

    operations = [
        migrations.RunPython(split_dates),
    ]
