# Generated by Django 3.2.5 on 2021-08-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_content', '0008_auto_20210831_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplementarycontent',
            name='date',
        ),
    ]
