# Generated by Django 3.2.7 on 2021-10-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_content', '0009_auto_20211004_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectgroup',
            name='subject_group_id',
            field=models.CharField(max_length=512),
        ),
    ]
