FROM ghcr.io/astral-sh/uv:0.9.22 AS uv

FROM public.ecr.aws/lambda/python:3.12 AS builder

ENV UV_COMPILE_BYTECODE=1
ENV UV_NO_INSTALLER_METADATA=1
ENV UV_LINK_MODE=copy
ENV UV_PROJECT_ENVIRONMENT=${LAMBDA_TASK_ROOT}/app/.venv

RUN --mount=from=uv,source=/uv,target=/bin/uv \
    --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=parsers/ecfr-worker/uv.lock,target=uv.lock \
    --mount=type=bind,source=parsers/ecfr-worker/pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=lambda-proxy/requirements.txt,target=lambda-proxy-requirements.txt \
    uv export --frozen --no-emit-workspace --no-editable -o requirements.txt && \
    uv pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}" && \
    uv pip install -r lambda-proxy-requirements.txt --target "${LAMBDA_TASK_ROOT}" && \
    uv sync --locked --no-install-project

FROM public.ecr.aws/lambda/python:3.12

ENV HOSTNAME="ecfr-worker"
ENV EXTERNAL_PORT="6000"
ENV PROXY_PARAMS=""
ENV STARTUP_CMD="app.app.handler"

COPY --from=builder ${LAMBDA_TASK_ROOT} ${LAMBDA_TASK_ROOT}
COPY lambda-proxy /proxy
COPY --from=uv /uv /bin/uv

COPY ./parsers/ecfr-worker ${LAMBDA_TASK_ROOT}/app
COPY ./parsers/common ${LAMBDA_TASK_ROOT}/common

ENTRYPOINT /proxy/startup.sh
