# Generated by Django 5.0.6 on 2024-05-31 12:33

from django.db import migrations, models

def populate_division_and_group(apps, schema_editor):
    Profile = apps.get_model('user', 'Profile')
    DepartmentGroup = apps.get_model('user', 'DepartmentGroup')
    DepartmentDivision = apps.get_model('user', 'DepartmentDivision')

    for profile in Profile.objects.all():
        department_parts = profile.department.split('/')
        if len(department_parts) >= 6:
            group_name = department_parts[5]
            department_group, _ = DepartmentGroup.objects.get_or_create(name=group_name)
            profile.department_group = department_group
        if len(department_parts) >= 7:
            division_name = department_parts[6]
            department_division, _ = DepartmentDivision.objects.get_or_create(name=division_name, department_group=profile.department_group)
            profile.department_division = department_division
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_departmentdivision_departmentgroup_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_division_and_group),
    ]
