# Generated by Django 5.0.4 on 2024-07-24 16:37

import common.fields
import common.mixins
import django.core.validators
import django.db.models.deletion
import django_jsonform.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('resources', '0001_initial'), ('resources', '0002_auto_20210712_1817'), ('resources', '0003_auto_20210820_2018'), ('resources', '0004_supplementarycontent_approved'), ('resources', '0005_auto_20210826_1455'), ('resources', '0006_alter_regulationsection_supplementary_content'), ('resources', '0007_auto_20210831_1612'), ('resources', '0008_auto_20211005_1906'), ('resources', '0009_alter_abstractsupplementalcontent_approved'), ('resources', '0010_abstractlocation_display_name'), ('resources', '0011_auto_20220211_1139'), ('resources', '0012_auto_20220223_1557'), ('resources', '0013_auto_20220302_1449'), ('resources', '0014_supplementalcontent_docket_number'), ('resources', '0015_supplementalcontent_document_number'), ('resources', '0016_v3_rewrite'), ('resources', '0017_create_docket_array'), ('resources', '0018_separate_docket_create_group'), ('resources', '0019_auto_group_fr_docs'), ('resources', '0020_abstractresource_related'), ('resources', '0021_frdoc_doc_type_and_config'), ('resources', '0022_populate_config_and_doc_type'), ('resources', '0023_delete_federalregistercategorylink'), ('resources', '0024_alter_federalregisterdocumentgroup_options'), ('resources', '0025_auto_20221027_0816'), ('resources', '0026_federalregisterdocument_location_history'), ('resources', '0027_auto_20230308_0918'), ('resources', '0028_set_name_sort'), ('resources', '0029_alter_federalregisterdocument_doc_type'), ('resources', '0030_auto_20230720_1427'), ('resources', '0031_abstractresource_subject'), ('resources', '0032_auto_20230912_1345'), ('resources', '0033_federalregisterdocument_raw_text_url'), ('resources', '0034_v4_refactor_models'), ('resources', '0035a_v4_refactor_data'), ('resources', '0035b_v4_refactor_data'), ('resources', '0035c_v4_refactor_data'), ('resources', '0035d_v4_refactor_data'), ('resources', '0035e_v4_refactor_data'), ('resources', '0035f_v4_refactor_data'), ('resources', '0035g_v4_refactor_data'), ('resources', '0035h_v4_refactor_data'), ('resources', '0035i_v4_refactor_data'), ('resources', '0036_alter_resourcegroup_options'), ('resources', '0037_detangle_file_manager'), ('resources', '0038_remove_v3_models'), ('resources', '0039_remove_old_pk_fields'), ('resources', '0040_rename_v4_models'), ('resources', '0041_alter_abstractresource_date'), ('resources', '0042_newresourcegroup'), ('resources', '0043_delete_resourcegroup'), ('resources', '0044_rename_newresourcegroup_resourcegroup'), ('resources', '0045_abstractresource_group_parent_and_more'), ('resources', '0046_abstractresource_related_categories_and_more'), ('resources', '0047_recompute_related_fields'), ('resources', '0048_remove_abstractresource_document_id_sort_and_more'), ('resources', '0049_remove_abstractresource_cfr_citation_history'), ('resources', '0050_remove_duplicated_groups'), ('resources', '0051_alter_abstractresource_document_id_and_more'), ('resources', '0052_alter_internalfile_options_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('show_if_empty', models.BooleanField(default=False)),
            ],
            bases=(models.Model, common.mixins.DisplayNameFieldMixin),
        ),
        migrations.CreateModel(
            name='AbstractCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
                ('part', models.IntegerField()),
            ],
            bases=(models.Model, common.mixins.DisplayNameFieldMixin),
        ),
        migrations.CreateModel(
            name='AbstractResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=True, help_text='Documents will be visible on eRegulations to all authorized users once they are approved.')),
                ('act_citations', common.fields.StatuteRefField(blank=True, default=list)),
                ('usc_citations', common.fields.UscRefField(blank=True, default=list, verbose_name='U.S. Code citations')),
                ('editor_notes', models.TextField(blank=True, help_text='Use this field to store notes meant for other editors. Notes in this field are not displayed outside this editing screen.')),
                ('document_id', models.CharField(blank=True, help_text='Some documents have an identifier, such as "SMDL #04-002" or "State Medicaid Manual Section 4442.3".', max_length=512, verbose_name='Document ID')),
                ('title', models.TextField(blank=True)),
                ('date', common.fields.VariableDateField(blank=True, help_text='Leave blank or enter the date the document was created or published. Some examples of valid dates are: "2024", "2024-01", or "2024-01-31".', max_length=10, validators=[common.fields.validate_date, django.core.validators.RegexValidator(message='Date field must be blank or of the format "YYYY", "YYYY-MM", or "YYYY-MM-DD". For example: 2021, 2021-01, or 2021-01-31.', regex='^\\d{4}((-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]))|(-(0[1-9]|1[0-2])))?$')])),
                ('url', models.URLField(blank=True, max_length=512, verbose_name='URL')),
                ('extract_url', models.URLField(blank=True, max_length=512, verbose_name='Extract URL')),
                ('group_parent', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Choose a single category or subcategory for the document. Choosing a subcategory will also apply the category when the document is listed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.abstractcategory')),
                ('cfr_citations', models.ManyToManyField(blank=True, help_text='Select regulation citations related to this document. Hold down "Control", or "Command" on a Mac, to select more than one.', related_name='resources', to='resources.abstractcitation', verbose_name='CFR citations')),
                ('related_categories', models.ManyToManyField(blank=True, to='resources.abstractcategory')),
                ('related_citations', models.ManyToManyField(blank=True, to='resources.abstractcitation')),
                ('related_resources', models.ManyToManyField(blank=True, to='resources.abstractresource')),
            ],
            bases=(models.Model, common.mixins.DisplayNameFieldMixin),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('combined_sort', common.fields.CombinedNaturalSort(['short_name', 'abbreviation', 'full_name'], db_index=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
            bases=(models.Model, common.mixins.DisplayNameFieldMixin),
        ),
        migrations.CreateModel(
            name='AbstractInternalCategory',
            fields=[
                ('abstractcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractcategory')),
            ],
            bases=('resources.abstractcategory',),
        ),
        migrations.CreateModel(
            name='AbstractPublicCategory',
            fields=[
                ('abstractcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractcategory')),
            ],
            bases=('resources.abstractcategory',),
        ),
        migrations.CreateModel(
            name='Subpart',
            fields=[
                ('abstractcitation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractcitation')),
                ('subpart_id', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Subpart',
                'verbose_name_plural': 'Subparts',
                'ordering': ['title', 'part', 'subpart_id'],
            },
            bases=('resources.abstractcitation',),
        ),
        migrations.CreateModel(
            name='AbstractInternalResource',
            fields=[
                ('abstractresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractresource')),
                ('summary', models.TextField(blank=True, help_text='Write two or three sentences as a preview of the document for others.')),
            ],
            bases=('resources.abstractresource',),
        ),
        migrations.CreateModel(
            name='AbstractPublicResource',
            fields=[
                ('abstractresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractresource')),
            ],
            bases=('resources.abstractresource',),
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='In leiu of (or in addition to) a list of common document identifiers, you may specify a name that identifies this group of documents.', max_length=512)),
                ('common_identifiers', django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512), blank=True, default=list, help_text='Common identifiers to use when grouping documents. For example, when grouping Federal Register Documents, use the docket number prefix, like "CMS-1234-".', size=None)),
                ('resources', models.ManyToManyField(blank=True, related_name='resource_groups', to='resources.abstractresource')),
            ],
            options={
                'verbose_name': 'Resource Group',
                'verbose_name_plural': 'Resource Groups',
                'ordering': ['name', 'common_identifiers'],
            },
        ),
        migrations.CreateModel(
            name='ResourcesConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_link_category', models.ForeignKey(blank=True, help_text='The category that contains Federal Register Links. This affects all newly uploaded Federal Register Links.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fr_link_category_config', to='resources.abstractcategory')),
            ],
            options={
                'verbose_name': 'Resources Configuration',
            },
        ),
        migrations.AddField(
            model_name='abstractresource',
            name='related_subjects',
            field=models.ManyToManyField(blank=True, to='resources.subject'),
        ),
        migrations.AddField(
            model_name='abstractresource',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Select subjects related to this document. Hold down "Control", or "Command" on a Mac, to select more than one.', related_name='resources', to='resources.subject'),
        ),
        migrations.CreateModel(
            name='InternalCategory',
            fields=[
                ('abstractinternalcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractinternalcategory')),
                ('name', models.CharField(max_length=512, unique=True)),
            ],
            options={
                'verbose_name': 'Internal Category',
                'verbose_name_plural': 'Internal Categories',
                'ordering': ['order', 'name'],
            },
            bases=('resources.abstractinternalcategory',),
        ),
        migrations.CreateModel(
            name='PublicCategory',
            fields=[
                ('abstractpubliccategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractpubliccategory')),
                ('name', models.CharField(max_length=512, unique=True)),
            ],
            options={
                'verbose_name': 'Public Category',
                'verbose_name_plural': 'Public Categories',
                'ordering': ['order', 'name'],
            },
            bases=('resources.abstractpubliccategory',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('abstractcitation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractcitation')),
                ('section_id', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resources.subpart')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['title', 'part', 'section_id'],
            },
            bases=('resources.abstractcitation',),
        ),
        migrations.CreateModel(
            name='InternalFile',
            fields=[
                ('abstractinternalresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractinternalresource')),
                ('file_name', models.CharField(blank=True, editable=False, max_length=512)),
                ('file_type', models.CharField(blank=True, editable=False, max_length=32)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'Internal File',
                'verbose_name_plural': 'Internal Files',
            },
            bases=('resources.abstractinternalresource',),
        ),
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('abstractinternalresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractinternalresource')),
            ],
            options={
                'verbose_name': 'Internal Link',
                'verbose_name_plural': 'Internal Links',
            },
            bases=('resources.abstractinternalresource',),
        ),
        migrations.CreateModel(
            name='FederalRegisterLink',
            fields=[
                ('abstractpublicresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractpublicresource')),
                ('docket_numbers', django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512), blank=True, default=list, size=None)),
                ('document_number', models.CharField(blank=True, help_text='This is a unique number for the rule that usually looks like "90-6614" and is listed at the very end of the rule.', max_length=255)),
                ('correction', models.BooleanField(default=False)),
                ('withdrawal', models.BooleanField(default=False)),
                ('action_type', models.CharField(blank=True, choices=[('RFI', 'RFI'), ('NPRM', 'NPRM'), ('Final', 'Final')], default='', max_length=32)),
            ],
            options={
                'verbose_name': 'Federal Register Link',
                'verbose_name_plural': 'Federal Register Links',
                'ordering': ['-date', 'document_number', 'document_id', 'title'],
            },
            bases=('resources.abstractpublicresource',),
        ),
        migrations.CreateModel(
            name='PublicLink',
            fields=[
                ('abstractpublicresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractpublicresource')),
            ],
            options={
                'verbose_name': 'Public Link',
                'verbose_name_plural': 'Public Links',
                'ordering': ['-date', 'document_id', 'title'],
            },
            bases=('resources.abstractpublicresource',),
        ),
        migrations.CreateModel(
            name='InternalSubCategory',
            fields=[
                ('abstractinternalcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractinternalcategory')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='resources.internalcategory')),
            ],
            options={
                'verbose_name': 'Internal Subcategory',
                'verbose_name_plural': 'Internal Subcategories',
                'ordering': ['order', 'name'],
            },
            bases=('resources.abstractinternalcategory',),
        ),
        migrations.CreateModel(
            name='PublicSubCategory',
            fields=[
                ('abstractpubliccategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractpubliccategory')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='resources.publiccategory')),
            ],
            options={
                'verbose_name': 'Public Subcategory',
                'verbose_name_plural': 'Public Subcategories',
                'ordering': ['order', 'name'],
            },
            bases=('resources.abstractpubliccategory',),
        ),
    ]
