# Generated by Django 5.0.7 on 2024-07-26 13:12
# Modified by Phil Reese and Caleb Godwin on 2024-07-26 14:12

import django.db.models.deletion
from django.db import migrations, models


def migrate_categories(apps, schema_editor):
    InternalCategory = apps.get_model("resources", "InternalCategory")
    InternalSubCategory = apps.get_model("resources", "InternalSubCategory")
    PublicCategory = apps.get_model("resources", "PublicCategory")
    PublicSubCategory = apps.get_model("resources", "PublicSubCategory")
    AbstractCategory = apps.get_model("resources", "AbstractCategory")

    for category in InternalCategory.objects.all():
        category.name = category.name_temp
        category.save()

    for category in PublicCategory.objects.all():
        category.name = category.name_temp
        category.save()

    for category in InternalSubCategory.objects.all():
        category.name = category.name_temp
        category.parent = category.parent_temp
        category.save()

    for category in PublicSubCategory.objects.all():
        category.name = category.name_temp
        category.parent = category.parent_temp
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_populate_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalcategory',
            old_name='name',
            new_name='name_temp',
        ),
        migrations.RenameField(
            model_name='internalsubcategory',
            old_name='name',
            new_name='name_temp',
        ),
        migrations.RenameField(
            model_name='publiccategory',
            old_name='name',
            new_name='name_temp',
        ),
        migrations.RenameField(
            model_name='publicsubcategory',
            old_name='name',
            new_name='name_temp',
        ),
        migrations.RenameField(
            model_name='publicsubcategory',
            old_name='parent',
            new_name='parent_temp',
        ),
        migrations.RenameField(
            model_name='internalsubcategory',
            old_name='parent',
            new_name='parent_temp',
        ),
        migrations.AddField(
            model_name='abstractcategory',
            name='name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='resources.abstractcategory'),
        ),
        migrations.RunPython(migrate_categories),
        migrations.RemoveField(
            model_name='internalcategory',
            name='name_temp',
        ),
        migrations.RemoveField(
            model_name='internalsubcategory',
            name='name_temp',
        ),
        migrations.RemoveField(
            model_name='internalsubcategory',
            name='parent_temp',
        ),
        migrations.RemoveField(
            model_name='publiccategory',
            name='name_temp',
        ),
        migrations.RemoveField(
            model_name='publicsubcategory',
            name='name_temp',
        ),
        migrations.RemoveField(
            model_name='publicsubcategory',
            name='parent_temp',
        ),
    ]
