# Generated by Django 5.0.7 on 2024-08-02 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_add_content_to_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesconfiguration',
            name='auto_extract',
            field=models.BooleanField(default=False, help_text='Check this box if eRegs should automatically request text extraction on any resource when its URL or attached file has changed.', verbose_name='Auto Extract'),
        ),
        migrations.AlterField(
            model_name='resourcesconfiguration',
            name='fr_link_category',
            field=models.ForeignKey(blank=True, help_text='The category that contains Federal Register Links. This affects all newly uploaded Federal Register Links.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fr_link_category_config', to='resources.abstractcategory', verbose_name='FR Link Category'),
        ),
    ]
