# Generated by Django 5.1.7 on 2025-05-05 16:50

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_recompute_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractcitation',
            options={'ordering': ['title', 'part', django.db.models.functions.comparison.Coalesce(models.Case(models.When(subpart__isnull=False, then='subpart__subpart_id'), models.When(section__isnull=False, then=django.db.models.functions.comparison.Cast('section__section_id', output_field=models.CharField())), default=models.Value(''), output_field=models.CharField()), models.Value(''))]},
        ),
    ]
