# Generated by Django 5.2.3 on 2025-06-11 23:35

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_update_ref_field_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesconfiguration',
            name='robots_txt_allow_list',
            field=django_jsonform.models.fields.JSONField(blank=True, default=list, help_text="A list of URLs that the text extractor should be allowed to access, even if eRegs is not in their robots.txt file. Use of asterisks (*) is allowed at the beginning or end of URLs to match any characters. For example, 'https://www.example.com/*' will allow access to all URLs under 'https://www.example.com/'.", verbose_name='Robots.txt Allow List'),
        ),
    ]
