# Generated by Django 5.2.3 on 2025-06-12 00:07

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_update_ref_field_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesconfiguration',
            name='robots_txt_allow_list',
            field=django_jsonform.models.fields.JSONField(blank=True, default=list, help_text="A list of URLs and/or domains that the text extractor should be allowed to access, even if eRegs is not in their robots.txt file. For example, 'example.com' will allow the entire domain and all subdomains to be accessed, while 'https://example.com/page.html' will allow only that specific page.", verbose_name='Robots.txt Allow List'),
        ),
    ]
