# Generated by Django 5.2.1 on 2025-06-17 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_resourcesconfiguration_robots_txt_allow_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesconfiguration',
            name='state_medicaid_manual_category',
            field=models.ForeignKey(blank=True, help_text='The category that contains State Medicaid Manual documents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smm_category_config', to='resources.abstractcategory', verbose_name='State Medicaid Manual Category'),
        ),
    ]
