# Generated by Django 5.2.3 on 2025-06-17 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_resourcesconfiguration_robots_txt_allow_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesconfiguration',
            name='extraction_delay_time',
            field=models.IntegerField(blank=True, default=180, help_text='The number of seconds to delay between multiple text extraction requests. This is useful to prevent overloading external services with too many requests in a short period of time.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Extraction Delay Time'),
        ),
    ]
