# Generated by Django 5.2.3 on 2025-07-16 16:20

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_resourcesconfiguration_extraction_delay_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesconfiguration',
            name='default_user_agent_override',
            field=models.CharField(blank=True, default='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:140.0) Gecko/20100101 Firefox/140.0', help_text="A default user agent to use for all requests to domains in the user agent override list that do not specify a user agent. This is useful for sites that block eRegs' default user agent.", max_length=255, verbose_name='Default User Agent Override'),
        ),
        migrations.AddField(
            model_name='resourcesconfiguration',
            name='user_agent_override_list',
            field=django_jsonform.models.fields.JSONField(blank=True, default=list, help_text="A list of domains and user agents that the text extractor should use instead of the default user agent. This is useful for sites that block eRegs' default user agent. Note that a domain will match all subdomains.", verbose_name='User Agent Override List'),
        ),
    ]
