# Generated by Django 5.2.3 on 2025-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_resourcesconfiguration_default_user_agent_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalfile',
            name='file_type',
        ),
        migrations.AddField(
            model_name='abstractresource',
            name='detected_file_type',
            field=models.CharField(blank=True, editable=False, help_text='The file type that the text extractor detected for this resource.', max_length=32),
        ),
        migrations.AddField(
            model_name='abstractresource',
            name='file_type',
            field=models.CharField(blank=True, help_text='The file type of the document. Only use this field if the automatically detected file type is incorrect, and the document content is not extracting correctly as a result.', max_length=32),
        ),
    ]
