# Generated by Django 3.2.12 on 2022-03-02 14:49

from itertools import chain

from django.db import migrations, models


def resave_models(apps, schema_editor):
    # try:
    #     from resources.models import AbstractLocation, AbstractCategory, AbstractResource
    #     for i in chain(AbstractLocation.objects.all(), AbstractCategory.objects.all(), AbstractResource.objects.all()):
    #         i.save()
    # except:
    #     pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_auto_20220223_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractcategory',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractlocation',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractsupplementalcontent',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(resave_models),
    ]
