# Generated by Django 3.2.12 on 2022-04-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_auto_20220302_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementalcontent',
            name='docket_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
