# Generated by Django 5.2.6 on 2025-09-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_remove_internalfile_file_type_and_more'),
        ('content_search', '0011_enable_chunking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractresource',
            name='detected_file_type',
        ),
        migrations.RemoveField(
            model_name='abstractresource',
            name='extraction_error',
        ),
        migrations.DeleteModel(
            name='ResourceContent',
        ),
    ]
