# Generated by Django 5.2.7 on 2025-12-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_remove_abstractresource_detected_file_type_and_more'),
        ('resources', '0014_sectioncontextbanner'),
    ]

    operations = [
    ]
