# Generated by Django 5.2.9 on 2026-02-03 15:27

import re

import django.db.models.deletion
from django.db import migrations, models

TIMEOUT_MINUTES = 15

def convert_citations(apps, schema_editor):
    # Set timeout
    schema_editor.execute(f"SET statement_timeout = '{TIMEOUT_MINUTES}min';")

    AbstractResource = apps.get_model('resources', 'AbstractResource')
    Act = apps.get_model('resources', 'Act')
    StatuteCitation = apps.get_model('resources', 'StatuteCitation')
    UscCitation = apps.get_model('resources', 'UscCitation')

    for resource in AbstractResource.objects.all():
        # Migrate act_citations_old to act_citations
        if resource.act_citations_old and type(resource.act_citations_old) == list:
            ids = []
            for i in resource.act_citations_old:
                act_name = i.get('act', 'Social Security Act').strip()
                section = re.sub(r"\s", "", i.get('section', ""))
                act, _ = Act.objects.get_or_create(name=act_name)
                statute_citation, _ = StatuteCitation.objects.get_or_create(
                    act=act,
                    section=section,
                )
                if statute_citation.id not in ids:
                    resource.act_citations.add(statute_citation)
                    ids.append(statute_citation.id)

        # Migrate usc_citations_old to usc_citations
        if resource.usc_citations_old and type(resource.usc_citations_old) == list:
            ids = []
            for i in resource.usc_citations_old:
                title = int(re.sub(r"\s", "", i.get('title')))
                section = re.sub(r"\s", "", i.get('section', ""))
                usc_citation, _ = UscCitation.objects.get_or_create(
                    title=title,
                    section=section,
                )
                if usc_citation.id not in ids:
                    resource.usc_citations.add(usc_citation)
                    ids.append(usc_citation.id)

        resource.save()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_merge_20251203_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractresource',
            old_name='act_citations',
            new_name='act_citations_old',
        ),
        migrations.RenameField(
            model_name='abstractresource',
            old_name='usc_citations',
            new_name='usc_citations_old',
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatuteCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=32)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statute_citations', to='resources.act')),
            ],
            options={
                'unique_together': {('act', 'section')},
                'verbose_name': 'Statute Citation',
                'verbose_name_plural': 'Statute Citations',
            },
        ),
        migrations.CreateModel(
            name='UscCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
                ('section', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('title', 'section')},
                'verbose_name': 'USC Citation',
                'verbose_name_plural': 'USC Citations',
            },
        ),
        migrations.AddField(
            model_name='abstractresource',
            name='act_citations',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.statutecitation'),
        ),
        migrations.AddField(
            model_name='abstractresource',
            name='usc_citations',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.usccitation'),
        ),
        migrations.RunPython(convert_citations),
        migrations.RemoveField(
            model_name='abstractresource',
            name='act_citations_old',
        ),
        migrations.RemoveField(
            model_name='abstractresource',
            name='usc_citations_old',
        ),
    ]
