# Generated by Django 5.2.9 on 2026-02-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_merge_20251203_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectioncontextbanner',
            options={'ordering': ['citation'], 'verbose_name': 'Context Banner', 'verbose_name_plural': 'Context Banners'},
        ),
    ]
