# Generated by Django 5.2.9 on 2026-02-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_merge_20251203_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federalregisterlink',
            name='action_type',
            field=models.CharField(blank=True, choices=[('Notice', 'Notice'), ('RFI', 'RFI'), ('NPRM', 'NPRM'), ('Final', 'Final')], default='', max_length=32),
        ),
    ]
