# Generated by Django 3.2.13 on 2022-06-30 15:10

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_v3_rewrite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='federalregisterdocument',
            options={'ordering': ['-date', 'document_number', 'name', 'description'], 'verbose_name': 'Federal Register Document', 'verbose_name_plural': 'Federal Register Documents'},
        ),
        migrations.AddField(
            model_name='federalregisterdocument',
            name='docket_numbers',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=list, blank=True, size=None),
        ),
    ]
