# Generated by Django 3.2.12 on 2022-05-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_v3_rewrite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractcategory',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='federalregisterdocument',
            options={'ordering': ['-date', 'document_number', 'docket_number', 'name', 'description'], 'verbose_name': 'Federal Register Document', 'verbose_name_plural': 'Federal Register Documents'},
        ),
        migrations.AlterModelOptions(
            name='supplementalcontent',
            options={'ordering': ['-date', 'name', 'description'], 'verbose_name': 'Supplemental Content', 'verbose_name_plural': 'Supplemental Content'},
        ),
    ]
