# Generated by Django 3.2.13 on 2022-07-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_auto_group_fr_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractresource',
            name='related_resources',
            field=models.ManyToManyField(blank=True, to='resources.AbstractResource'),
        ),
    ]
