# Generated by Django 5.2.9 on 2026-02-11 14:37

import common.fields
from django.db import migrations


def populate_sort_fields(apps, schema_editor):
    StatuteCitation = apps.get_model('resources', 'StatuteCitation')
    UscCitation = apps.get_model('resources', 'UscCitation')

    for citation in StatuteCitation.objects.all():
        citation.section_sort = common.fields.NaturalSortField(for_field='section').clean(citation.section, citation)
        citation.save(update_fields=['section_sort'])

    for citation in UscCitation.objects.all():
        citation.section_sort = common.fields.NaturalSortField(for_field='section').clean(citation.section, citation)
        citation.save(update_fields=['section_sort'])


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_recompute_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['name'], 'verbose_name': 'Act', 'verbose_name_plural': 'Acts'},
        ),
        migrations.AlterModelOptions(
            name='statutecitation',
            options={'ordering': ['act__name', 'section_sort'], 'verbose_name': 'Statute Citation', 'verbose_name_plural': 'Statute Citations'},
        ),
        migrations.AlterModelOptions(
            name='usccitation',
            options={'ordering': ['title', 'section_sort'], 'verbose_name': 'USC Citation', 'verbose_name_plural': 'USC Citations'},
        ),
        migrations.AddField(
            model_name='statutecitation',
            name='section_sort',
            field=common.fields.NaturalSortField('section', db_index=True, default='', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usccitation',
            name='section_sort',
            field=common.fields.NaturalSortField('section', db_index=True, default='', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(populate_sort_fields, reverse_code=migrations.RunPython.noop),
    ]
