# Generated by Django 5.2.9 on 2026-02-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_alter_act_options_alter_statutecitation_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatuteCitation',
            new_name='ActCitation',
        ),
        migrations.AlterField(
            model_name='abstractresource',
            name='act_citations',
            field=models.ManyToManyField(blank=True, help_text='Select act citations related to this document. Hold down "Control", or "Command" on a Mac, to select more than one.', related_name='resources', to='resources.actcitation'),
        ),
        migrations.AlterField(
            model_name='abstractresource',
            name='related_act_citations',
            field=models.ManyToManyField(blank=True, to='resources.actcitation'),
        ),
    ]
