# Generated by Django 3.2.15 on 2022-08-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_abstractresource_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalregisterdocument',
            name='doc_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ResourcesConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_doc_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.abstractcategory', related_name='fr_doc_category_config', help_text='The category that contains Federal Register Documents. This affects all newly uploaded Federal Register Documents.')),
            ],
            options={
                'verbose_name': 'Resources Configuration',
            },
        ),
    ]
