# Generated by Django 3.2.15 on 2022-08-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_abstractresource_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalregisterdocument',
            name='doc_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
