# Generated by Django 6.0.3 on 2026-08-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_actcitation_alter_abstractresource_act_citations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actcitation',
            options={'ordering': ['act__name', 'section_sort'], 'verbose_name': 'Act Citation', 'verbose_name_plural': 'Act Citations'},
        ),
        migrations.AlterField(
            model_name='abstractresource',
            name='act_citations',
            field=models.ManyToManyField(blank=True, help_text='Select Act citations related to this document. Hold down "Control", or "Command" on a Mac, to select more than one.', related_name='resources', to='resources.actcitation'),
        ),
        migrations.AlterField(
            model_name='actcitation',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_citations', to='resources.act'),
        ),
    ]
