# Generated by Django 3.2.15 on 2022-08-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_convert_categories_to_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_doc_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.abstractcategory')),
            ],
            options={
                'verbose_name': 'Resources Configuration',
                'verbose_name_plural': 'Resources Configuration',
            },
        ),
    ]
