# Generated by Django 3.2.13 on 2022-08-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_populate_config_and_doc_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FederalRegisterCategoryLink',
        ),
    ]
