# Generated by Django 3.2.15 on 2022-09-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_delete_federalregistercategorylink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='federalregisterdocumentgroup',
            options={'ordering': ('docket_number_prefixes',), 'verbose_name': 'Federal Register Doc Group', 'verbose_name_plural': 'Federal Register Doc Groups'},
        ),
    ]
