# Generated by Django 3.2.16 on 2022-10-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_alter_federalregisterdocumentgroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalregisterdocument',
            name='correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='federalregisterdocument',
            name='withdrawal',
            field=models.BooleanField(default=False),
        ),
    ]
