# Generated by Django 3.2.16 on 2022-10-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_alter_federalregisterdocumentgroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalregisterdocument',
            name='location_history',
            field=models.JSONField(default=list),
        ),
    ]
