# Generated by Django 3.2.16 on 2022-10-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_auto_20221027_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalregisterdocument',
            name='location_history',
            field=models.JSONField(default=list),
        ),
    ]
