# Generated by Django 3.2.18 on 2023-03-08 09:18

from django.db import migrations
import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0026_federalregisterdocument_location_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalregisterdocument',
            name='description_sort',
            field=common.fields.NaturalSortField('description', db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='federalregisterdocument',
            name='name_sort',
            field=common.fields.NaturalSortField('name', db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplementalcontent',
            name='description_sort',
            field=common.fields.NaturalSortField('description', db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplementalcontent',
            name='name_sort',
            field=common.fields.NaturalSortField('name', db_index=True, editable=False, max_length=255, null=True),
        ),
    ]
