# Generated by Django 3.2.19 on 2023-05-30 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0029_alter_federalregisterdocument_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalDocument',
            fields=[
                ('abstractresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractresource')),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, help_text='Leave blank or enter one of: "YYYY", "YYYY-MM", or "YYYY-MM-DD".', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Date field must be blank or of format "YYYY", "YYYY-MM", or "YYYY-MM-DD"! For example: 2021, 2021-01, or 2021-01-31.', regex='^\\d{4}((-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]))|(-(0[1-9]|1[0-2])))?$')])),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=512, null=True)),
                ('name_sort', resources.models.NaturalSortField('name', db_index=True, editable=False, max_length=255, null=True)),
                ('description_sort', resources.models.NaturalSortField('description', db_index=True, editable=False, max_length=255, null=True)),
                ('internal_document', models.FileField(upload_to='documents/')),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.abstractresource', models.Model),
        ),
    ]
