# Generated by Django 3.2.18 on 2023-03-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0029_location_newcategory_newcategorycategory_newcategorysubcategory_newfederalregisterdocument_newfedera'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('title', 'part', 'section'), ('title', 'part', 'subpart')},
        ),
    ]
