# Generated by Django 3.2.20 on 2023-08-09 13:15

import common.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0030_auto_20230720_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypicalResource',
            fields=[
                ('abstractresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.abstractresource')),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=512, null=True)),
                ('name_sort', common.fields.NaturalSortField('name', db_index=True, editable=False, max_length=255, null=True)),
                ('description_sort', common.fields.NaturalSortField('description', db_index=True, editable=False, max_length=255, null=True)),
                ('date', common.fields.VariableDateField(blank=True, help_text='Leave blank or enter one of: "YYYY", "YYYY-MM", or "YYYY-MM-DD".', max_length=10, null=True, validators=[common.fields.validate_date, django.core.validators.RegexValidator(message='Date field must be blank or of the format "YYYY", "YYYY-MM", or "YYYY-MM-DD". For example: 2021, 2021-01, or 2021-01-31.', regex='^\\d{4}((-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]))|(-(0[1-9]|1[0-2])))?$')])),
            ],
            options={
                'verbose_name': 'TypicalResource',
                'verbose_name_plural': 'Typical Resources',
                'ordering': ['-date', 'name', 'description'],
            },
            bases=('resources.abstractresource', models.Model),
        ),
        migrations.CreateModel(
            name='InternalDocument',
            fields=[
                ('typicalresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.typicalresource')),
            ],
            options={
                'verbose_name': 'Internal Document',
                'verbose_name_plural': 'Internal Documents',
                'ordering': ['-date', 'name', 'description'],
            },
            bases=('resources.typicalresource',),
        ),
    ]
