# Generated by Django 3.2.20 on 2023-08-24 15:40

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('resources', '0030_auto_20230720_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='test_file', to='filer.file')),
            ],
        ),
    ]
