# Generated by Django 3.2.20 on 2023-09-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0009_auto_20230831_1303'),
        ('resources', '0030_auto_20230720_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractresource',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='resources', to='file_manager.Subject'),
        ),
    ]
