# Generated by Django 3.2.19 on 2023-05-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0030_internaldocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internaldocument',
            name='url',
        ),
    ]
