# Generated by Django 3.2.18 on 2023-03-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0030_migrate_resource_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractresource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='abstractresource',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='abstractresource',
            name='related_resources',
        ),
        migrations.RemoveField(
            model_name='category',
            name='abstractcategory_ptr',
        ),
        migrations.RemoveField(
            model_name='federalregisterdocument',
            name='abstractresource_ptr',
        ),
        migrations.RemoveField(
            model_name='federalregisterdocument',
            name='group',
        ),
        migrations.RemoveField(
            model_name='resourcesconfiguration',
            name='fr_doc_category',
        ),
        migrations.RemoveField(
            model_name='section',
            name='abstractlocation_ptr',
        ),
        migrations.RemoveField(
            model_name='section',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='abstractcategory_ptr',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subpart',
            name='abstractlocation_ptr',
        ),
        migrations.RemoveField(
            model_name='supplementalcontent',
            name='abstractresource_ptr',
        ),
        migrations.DeleteModel(
            name='AbstractCategory',
        ),
        migrations.DeleteModel(
            name='AbstractLocation',
        ),
        migrations.DeleteModel(
            name='AbstractResource',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FederalRegisterDocument',
        ),
        migrations.DeleteModel(
            name='FederalRegisterDocumentGroup',
        ),
        migrations.DeleteModel(
            name='ResourcesConfiguration',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='Subpart',
        ),
        migrations.DeleteModel(
            name='SupplementalContent',
        ),
    ]
