# Generated by Django 3.2.20 on 2023-08-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0031_customdocument_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
