# Generated by Django 3.2.18 on 2023-03-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0031_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcegroup',
            unique_together={('type', 'docket_number_prefixes')},
        ),
    ]
