# Generated by Django 3.2.20 on 2023-09-12 13:45

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0031_abstractresource_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractresource',
            name='statute_locations',
            field=common.fields.StatuteRefField(blank=True, default=list, verbose_name='Statute Reference Locations'),
        ),
        migrations.AddField(
            model_name='abstractresource',
            name='usc_locations',
            field=common.fields.UscRefField(blank=True, default=list, verbose_name='U.S.C. Reference Locations'),
        ),
    ]
