# Generated by Django 3.2.18 on 2023-03-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0031_auto_20230317_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCategoryCategory',
        ),
        migrations.DeleteModel(
            name='NewCategorySubCategory',
        ),
        migrations.DeleteModel(
            name='NewFederalRegisterDocument',
        ),
        migrations.DeleteModel(
            name='NewFederalRegisterDocumentGroup',
        ),
        migrations.DeleteModel(
            name='NewSupplementalContent',
        ),
        migrations.DeleteModel(
            name='SectionLocation',
        ),
        migrations.DeleteModel(
            name='SubpartLocation',
        ),
        migrations.RenameModel(
            old_name='NewCategory',
            new_name='BaseCategory',
        ),
        migrations.RenameModel(
            old_name='NewResourcesConfiguration',
            new_name='ResourcesConfiguration',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.basecategory',),
        ),
        migrations.CreateModel(
            name='FederalRegisterDocument',
            fields=[
            ],
            options={
                'verbose_name': 'Federal Register Document',
                'verbose_name_plural': 'Federal Register Documents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='FederalRegisterDocumentGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Federal Register Doc Group',
                'verbose_name_plural': 'Federal Register Doc Groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.resourcegroup',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.location',),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Sub-category',
                'verbose_name_plural': 'Sub-categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.basecategory',),
        ),
        migrations.CreateModel(
            name='Subpart',
            fields=[
            ],
            options={
                'verbose_name': 'Subpart',
                'verbose_name_plural': 'Subparts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.location',),
        ),
        migrations.CreateModel(
            name='SupplementalContent',
            fields=[
            ],
            options={
                'verbose_name': 'Supplemental Content',
                'verbose_name_plural': 'Supplemental Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.resource',),
        ),
    ]
