# Generated by Django 3.2.19 on 2023-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0031_remove_internaldocument_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldocument',
            name='author',
            field=models.CharField(default='bob', max_length=512),
            preserve_default=False,
        ),
    ]
