# Generated by Django 3.2.20 on 2023-08-14 11:42

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('resources', '0032_customdocument_internalcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldocument',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
