# Generated by Django 3.2.24 on 2024-03-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0032_auto_20230912_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalregisterdocument',
            name='raw_text_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
