# Generated by Django 3.2.20 on 2023-08-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0033_internaldocument_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldocument',
            name='file',
            field=models.FileField(default=None, upload_to='specs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abstractresource',
            name='location_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
