# Generated by Django 3.2.20 on 2023-08-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0034_auto_20230814_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdocument',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='document', to='resources.AbstractLocation'),
        ),
    ]
