# Generated by Django 5.0.4 on 2024-05-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0035_v4_refactor_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcegroup',
            options={'ordering': ['name', 'common_identifiers'], 'verbose_name': 'Resource Group', 'verbose_name_plural': 'Resource Groups'},
        ),
    ]
