# Generated by Django 3.2.20 on 2023-08-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0036_auto_20230815_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdocument',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
