# Generated by Django 5.0.4 on 2024-05-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0036_alter_resourcegroup_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractresource',
            name='subjects',
        ),
    ]
