# Generated by Django 5.0.4 on 2024-05-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0011_remove_contentindex_category_and_more'),
        ('resources', '0037_detangle_file_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='abstractcategory_ptr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='abstractcategory_ptr',
        ),
        migrations.RemoveField(
            model_name='abstractresource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='section',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subpart',
            name='abstractlocation_ptr',
        ),
        migrations.RemoveField(
            model_name='abstractresource',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='section',
            name='abstractlocation_ptr',
        ),
        migrations.RemoveField(
            model_name='abstractresource',
            name='related_resources',
        ),
        migrations.RemoveField(
            model_name='supplementalcontent',
            name='abstractresource_ptr',
        ),
        migrations.RemoveField(
            model_name='federalregisterdocument',
            name='abstractresource_ptr',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='federalregisterdocument',
            name='group',
        ),
        migrations.DeleteModel(
            name='ResourcesConfiguration',
        ),
        migrations.DeleteModel(
            name='AbstractCategory',
        ),
        migrations.DeleteModel(
            name='Subpart',
        ),
        migrations.DeleteModel(
            name='AbstractLocation',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SupplementalContent',
        ),
        migrations.DeleteModel(
            name='AbstractResource',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='FederalRegisterDocument',
        ),
        migrations.DeleteModel(
            name='FederalRegisterDocumentGroup',
        ),
    ]
