# Generated by Django 5.0.4 on 2024-05-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0038_remove_v3_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractcitation',
            name='old_pk',
        ),
        migrations.RemoveField(
            model_name='abstractinternalcategory',
            name='old_pk',
        ),
        migrations.RemoveField(
            model_name='abstractinternalresource',
            name='old_pk',
        ),
        migrations.RemoveField(
            model_name='abstractpubliccategory',
            name='old_pk',
        ),
        migrations.RemoveField(
            model_name='abstractpublicresource',
            name='old_pk',
        ),
        migrations.RemoveField(
            model_name='newsubject',
            name='old_pk',
        ),
    ]
