# Generated by Django 5.0.4 on 2024-06-14 15:02

import common.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0040_rename_v4_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractresource',
            name='date',
            field=common.fields.VariableDateField(blank=True, default='', help_text='Leave blank or enter the date the document was created or published. Some examples of valid dates are: "2024", "2024-01", or "2024-01-31".', max_length=10, validators=[common.fields.validate_date, django.core.validators.RegexValidator(message='Date field must be blank or of the format "YYYY", "YYYY-MM", or "YYYY-MM-DD". For example: 2021, 2021-01, or 2021-01-31.', regex='^\\d{4}((-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]))|(-(0[1-9]|1[0-2])))?$')]),
            preserve_default=False,
        ),
    ]
