# Generated by Django 5.0.6 on 2024-06-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0042_newresourcegroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceGroup',
        ),
    ]
