# Generated by Django 5.0.6 on 2024-06-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0043_delete_resourcegroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewResourceGroup',
            new_name='ResourceGroup',
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='resource_groups', to='resources.abstractresource'),
        ),
    ]
