# Generated by Django 5.0.6 on 2024-06-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0044_rename_newresourcegroup_resourcegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractresource',
            name='group_parent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='abstractresource',
            name='related_resources',
            field=models.ManyToManyField(blank=True, to='resources.abstractresource'),
        ),
    ]
