# Generated by Django 5.0.6 on 2024-07-02 14:45

from django.db import migrations, models
from django.db.models import Value, Q
from django.contrib.postgres.aggregates import ArrayAgg



def generate_related(apps, schema_editor):
    # This is superseded by 0047's generate_related function
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0045_abstractresource_group_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractresource',
            name='related_categories',
            field=models.ManyToManyField(blank=True, to='resources.abstractcategory'),
        ),
        migrations.AddField(
            model_name='abstractresource',
            name='related_citations',
            field=models.ManyToManyField(blank=True, to='resources.abstractcitation'),
        ),
        migrations.AddField(
            model_name='abstractresource',
            name='related_subjects',
            field=models.ManyToManyField(blank=True, to='resources.subject'),
        ),
        migrations.RunPython(generate_related),
    ]
