# Generated by Django 5.0.6 on 2024-07-02 14:45

from django.db import migrations, models
from django.db.models import Value, Q
from django.contrib.postgres.aggregates import ArrayAgg



def generate_related(apps, schema_editor):
    AbstractResource = apps.get_model("resources", "AbstractResource")
    for resource in AbstractResource.objects.all():
        groups = resource.resource_groups.all()
        AbstractResource.objects.filter(resource_groups__in=groups).update(group_parent=False)
        for group in groups:
            group.resources.filter(pk=group.resources.order_by("-date").first().pk).update(group_parent=True)
        related_resources = AbstractResource.objects.filter(resource_groups__in=groups).exclude(pk=resource.pk)
        related_aggregates = related_resources.aggregate(
            all_citations=ArrayAgg("cfr_citations", distinct=True, filter=Q(cfr_citations__isnull=False), default=Value([])),
            all_categories=ArrayAgg("category", distinct=True, filter=Q(category__isnull=False), default=Value([])),
            all_subjects=ArrayAgg("subjects", distinct=True, filter=Q(subjects__isnull=False), default=Value([])),
        )

        resource.related_resources.set(related_resources)
        resource.related_citations.set(related_aggregates["all_citations"])
        resource.related_categories.set(related_aggregates["all_categories"])
        resource.related_subjects.set(related_aggregates["all_subjects"])


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0045_abstractresource_group_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractresource',
            name='related_categories',
            field=models.ManyToManyField(blank=True, to='resources.abstractcategory'),
        ),
        migrations.AddField(
            model_name='abstractresource',
            name='related_citations',
            field=models.ManyToManyField(blank=True, to='resources.abstractcitation'),
        ),
        migrations.AddField(
            model_name='abstractresource',
            name='related_subjects',
            field=models.ManyToManyField(blank=True, to='resources.subject'),
        ),
        migrations.RunPython(generate_related),
    ]
