# Generated by Django 5.0.7 on 2024-07-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0047_recompute_related_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractresource',
            name='document_id_sort',
        ),
        migrations.RemoveField(
            model_name='abstractresource',
            name='title_sort',
        ),
    ]
