# Generated by Django 5.0.4 on 2024-07-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0047_recompute_related_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractresource',
            name='cfr_citation_history',
        ),
    ]
