# Generated by Django 5.0.4 on 2024-07-11 13:23

from django.db import migrations


TIMEOUT_MINUTES = 10


def same(a, b):
    return a["common_identifiers"] == b["common_identifiers"] and a["name"] == b["name"]


def remove_duplicated_groups(apps, schema_editor):
    schema_editor.execute(f"SET LOCAL statement_timeout TO {TIMEOUT_MINUTES * 60000};")
    ResourceGroup = apps.get_model("resources", "ResourceGroup")
    groups = list(ResourceGroup.objects.values("common_identifiers", "name", "pk"))
    keep = []
    discard = []

    for i in groups:
        for j in keep:
            if same(i, j):
                discard.append(i)
                break
        keep.append(i)

    pks = [i["pk"] for i in discard]
    ResourceGroup.objects.filter(pk__in=pks).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0049_remove_abstractresource_cfr_citation_history'),
    ]

    operations = [
        migrations.RunPython(remove_duplicated_groups),
    ]
