# Generated by Django 5.0.4 on 2024-07-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0050_remove_duplicated_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractresource',
            name='document_id',
            field=models.CharField(blank=True, help_text='Some documents have an identifier, such as "SMDL #04-002" or "State Medicaid Manual Section 4442.3".', max_length=512, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='abstractresource',
            name='url',
            field=models.URLField(blank=True, max_length=512, verbose_name='URL'),
        ),
    ]
