# Generated by Django 5.0.7 on 2024-07-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0051_alter_abstractresource_document_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalfile',
            options={'verbose_name': 'Internal File', 'verbose_name_plural': 'Internal Files'},
        ),
        migrations.AlterModelOptions(
            name='internallink',
            options={'verbose_name': 'Internal Link', 'verbose_name_plural': 'Internal Links'},
        ),
    ]
