// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomNavBtnGroup: typeof import('./src/components/navigation/BottomNavBtnGroup.vue')['default']
    CategoryList: typeof import('./src/components/custom_elements/CategoryList.vue')['default']
    FancyDropdown: typeof import('./src/components/custom_elements/FancyDropdown.vue')['default']
    NavBtn: typeof import('./src/components/navigation/NavBtn.vue')['default']
    PageNumber: typeof import('./src/components/pagination/PageNumber.vue')['default']
    PagesList: typeof import('./src/components/pagination/PagesList.vue')['default']
    PaginationController: typeof import('./src/components/pagination/PaginationController.vue')['default']
    ResourcesFilters: typeof import('./src/components/resources/ResourcesFilters.vue')['default']
    ResourcesNav: typeof import('./src/components/resources/ResourcesNav.vue')['default']
    ResourcesResults: typeof import('./src/components/resources/ResourcesResults.vue')['default']
    ResourcesSelections: typeof import('./src/components/resources/ResourcesSelections.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchEmptyState: typeof import('./src/components/SearchEmptyState.vue')['default']
    SectionList: typeof import('./src/components/custom_elements/SectionList.vue')['default']
    SubpartList: typeof import('./src/components/custom_elements/SubpartList.vue')['default']
    TitlePartList: typeof import('./src/components/custom_elements/TitlePartList.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VChip: typeof import('vuetify/lib')['VChip']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VerticalRule: typeof import('./src/components/navigation/VerticalRule.vue')['default']
    VLabel: typeof import('vuetify/lib')['VLabel']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemGroup: typeof import('vuetify/lib')['VListItemGroup']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VRow: typeof import('vuetify/lib')['VRow']
    VTextarea: typeof import('vuetify/lib')['VTextarea']
    VTextField: typeof import('vuetify/lib')['VTextField']
  }
}

export {}
