# Generated by Django 3.2.20 on 2023-08-28 11:22

import common.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0030_auto_20230720_1427'),
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='date',
            field=common.fields.VariableDateField(blank=True, help_text='Leave blank or enter one of: "YYYY", "YYYY-MM", or "YYYY-MM-DD".', max_length=10, null=True, validators=[common.fields.validate_date, django.core.validators.RegexValidator(message='Date field must be blank or of the format "YYYY", "YYYY-MM", or "YYYY-MM-DD". For example: 2021, 2021-01, or 2021-01-31.', regex='^\\d{4}((-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]))|(-(0[1-9]|1[0-2])))?$')]),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='locations', to='resources.AbstractLocation'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category', to='file_manager.UploadCategory'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='subject', to='file_manager.Subject'),
        ),
    ]
