# Generated by Django 3.2.20 on 2023-08-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0030_auto_20230720_1427'),
        ('file_manager', '0003_auto_20230828_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='uploads', to='file_manager.UploadCategory'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='uploads', to='resources.AbstractLocation'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='uploads', to='file_manager.Subject'),
        ),
    ]
