# Generated by Django 3.2.20 on 2023-08-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0004_auto_20230828_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='categories',
            new_name='category',
        ),
    ]
