# Generated by Django 3.2.20 on 2023-08-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0005_rename_categories_uploadedfile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcategory',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='category',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='file_manager.uploadcategory'),
        ),
    ]
