# Generated by Django 3.2.20 on 2023-08-30 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0006_auto_20230830_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Document Types',
            },
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='order',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='category',
        ),
        migrations.AddField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='UploadCategory',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='file_manager.documenttype'),
        ),
    ]
