# Generated by Django 3.2.20 on 2023-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0007_auto_20230830_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='filepath',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
