# Generated by Django 3.2.20 on 2023-08-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0008_auto_20230831_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='filepath',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default=None, upload_to='uploaded_files/'),
            preserve_default=False,
        ),
    ]
