# Generated by Django 3.2.20 on 2023-09-08 11:34

from django.db import migrations, models

def set_file_name(apps, schema_editor):
    internal_documents = apps.get_model("file_manager", "uploadedfile")

    for doc in internal_documents.objects.all():
        doc.file_name = doc.file.name.split("/")[1]
        doc.save()
class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0009_auto_20230831_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.RunPython(set_file_name),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
    ]
