# Generated by Django 3.2.20 on 2023-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0032_auto_20230912_1345'),
        ('file_manager', '0010_set_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='name',
            new_name='document_id',
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='description',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='uploads', to='resources.AbstractLocation', verbose_name='Regulation Locations'),
        ),
    ]
