# Generated by Django 3.2.22 on 2023-10-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0011_auto_20230925_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='document_id',
            new_name='document_name',
        ),
    ]
