# Generated by Django 3.2.22 on 2023-10-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0012_rename_document_id_uploadedfile_document_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='subject',
            new_name='subjects',
        ),
    ]
