# Generated by Django 3.2.22 on 2023-11-14 07:44

import common.fields
from django.db import migrations

def add_sort_field(apps, schema_editor):
    subject_model = apps.get_model("file_manager", "Subject")
    subjects = subject_model.objects.all()

    for subject in subjects:
        subject.save()

class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0013_rename_subject_uploadedfile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='combined_sort',
            field=common.fields.CombinedNaturalSort(['short_name', 'abbreviation', 'full_name'], db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.RunPython(add_sort_field),
    ]
