# Generated by Django 3.2.23 on 2023-12-07 16:15

import common.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0014_subject_combined_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractRepoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('show_if_empty', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=(models.Model, common.mixins.DisplayNameFieldMixin),
        ),
        migrations.CreateModel(
            name='RepositoryCategory',
            fields=[
                ('abstractrepocategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file_manager.abstractrepocategory')),
            ],
            options={
                'verbose_name': 'Repository Category',
                'verbose_name_plural': 'Repository Categories',
            },
            bases=('file_manager.abstractrepocategory',),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='file_manager.abstractrepocategory'),
        ),
        migrations.CreateModel(
            name='RepositorySubCategory',
            fields=[
                ('abstractrepocategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='file_manager.abstractrepocategory')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='file_manager.repositorycategory')),
            ],
            options={
                'verbose_name': 'Repository Sub-category',
                'verbose_name_plural': 'Repository Sub-categories',
            },
            bases=('file_manager.abstractrepocategory',),
        ),
    ]
