# Generated by Django 3.2.24 on 2024-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0015_auto_20231207_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
