# Generated by Django 3.2.24 on 2024-03-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0010_remove_contentindex_document_type'),
        ('file_manager', '0017_auto_20240301_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='document_type',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
