# Generated by Django 3.2.25 on 2024-03-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0017_auto_20240301_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
