# Generated by Django 5.0.4 on 2024-05-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_search', '0011_remove_v3_dependencies'),
        ('file_manager', '0018_auto_20240313_1400'),
        ('resources', '0037_detangle_file_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorycategory',
            name='abstractrepocategory_ptr',
        ),
        migrations.RemoveField(
            model_name='repositorysubcategory',
            name='abstractrepocategory_ptr',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='division',
            name='group',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='division',
        ),
        migrations.RemoveField(
            model_name='repositorysubcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='locations',
        ),
        migrations.DeleteModel(
            name='AbstractRepoCategory',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='RepositoryCategory',
        ),
        migrations.DeleteModel(
            name='RepositorySubCategory',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
