# Generated by Django 3.2.12 on 2022-02-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplemental_content', '0009_alter_abstractsupplementalcontent_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractlocation',
            name='display_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
