# Generated by Django 3.2.12 on 2022-02-23 15:57

from itertools import chain

from django.db import migrations, models


def resave_models(apps, schema_editor):
    try:
        from supplemental_content.models import AbstractCategory, AbstractSupplementalContent
        for model in chain(AbstractCategory.objects.all(), AbstractSupplementalContent.objects.all()):
            model.save()
    except: # Primarily ImportError but safer to catch everything
        pass # Skip in case model is changed, renamed, or deleted in the future


class Migration(migrations.Migration):

    dependencies = [
        ('supplemental_content', '0011_auto_20220211_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractcategory',
            name='display_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='abstractsupplementalcontent',
            name='display_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RunPython(resave_models),
    ]
