# Generated by Django 3.2.12 on 2022-05-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplemental_content', '0015_supplementalcontent_document_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubSubCategory',
        ),
        migrations.AlterModelOptions(
            name='abstractlocation',
            options={'ordering': ['title', 'part', 'section__section_id', 'subpart__subpart_id']},
        ),
        migrations.RemoveField(
            model_name='abstractcategory',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='abstractlocation',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='abstractsupplementalcontent',
            name='display_name',
        ),
        migrations.DeleteModel(
            name='SubjectGroup',
        ),
    ]
