# Generated by Django 3.2.12 on 2022-05-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplemental_content', '0015_supplementalcontent_document_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubSubCategory',
        ),
    ]
