# Generated by Django 3.2.12 on 2022-05-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplemental_content', '0016_v3_rewrite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplementalContent',
            new_name='TempSupplementalContent',
        ),
    ]
