reg_site:
  environment:
    STATIC_URL: ${self:custom.settings.static_url}
    WORKING_DIR: /var/task
  handler: wsgi_handler.handler
  layers:
    - ${cf:cmcs-eregs-static-assets-${self:custom.stage}.PythonRequirementsLambdaLayerQualifiedArn}
  events:
    - http: ANY /
    - http: ANY {proxy+}
  timeout: 20
reg_core_migrate:
  handler: migrate.handler
  layers:
    - ${cf:cmcs-eregs-static-assets-${self:custom.stage}.PythonRequirementsLambdaLayerQualifiedArn}
  timeout: 300
create_su:
  handler: createsu.handler
  layers:
    - ${cf:cmcs-eregs-static-assets-${self:custom.stage}.PythonRequirementsLambdaLayerQualifiedArn}
  timeout: 300
