# Generated by Django 3.2.18 on 2026-08-24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import solo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParserConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workers', models.IntegerField(default=3, help_text='The number of worker threads used to parse simultaneously.', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Number of workers must be at least 1!')])),
                ('retries', models.IntegerField(default=3, help_text='The number of times to retry parsing before moving on if it fails.', validators=[django.core.validators.MinValueValidator(limit_value=0, message='The number of retries must be at least 0!')])),
                ('loglevel', models.CharField(choices=[('fatal', 'Fatal'), ('error', 'Error'), ('warn', 'Warning'), ('info', 'Info'), ('debug', 'Debug'), ('trace', 'Trace')], default='warn', help_text="Specifies the level of detail contained in the parser's logs.", max_length=5)),
                ('upload_supplemental_locations', models.BooleanField(default=True, help_text='Should the eCFR parser process and upload section and subpart names for use in resource management?')),
                ('log_parse_errors', models.BooleanField(default=False, help_text='Should the eCFR parser log errors encountered while processing the raw XML data from eCFR?')),
                ('skip_reg_versions', models.BooleanField(default=True, help_text='Should the eCFR parser skip processing versions of regulation parts that have been previously processed?')),
                ('skip_fr_documents', models.BooleanField(default=True, help_text='Should the Federal Register parser skip processing documents that have been previously processed?')),
            ],
            options={
                'verbose_name': 'Parser Configuration',
            },
            bases=(solo.models.SingletonModel, models.Model),
        ),
        migrations.CreateModel(
            name='AbstractParserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('title', models.IntegerField()),
                ('subchapters', models.TextField(blank=True)),
                ('parts', models.TextField(blank=True)),
                ('workers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PartConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(help_text='The title of the regulations to parse, e.g. 42.')),
                ('type', models.CharField(choices=[('subchapter', 'Subchapter'), ('part', 'Part')], default='part', max_length=255)),
                ('value', models.CharField(help_text='A subchapter or part to parse. E.g., "IV-C" or "400".', max_length=255, validators=[django.core.validators.RegexValidator(message='Please enter a valid part or subchapter, e.g. "IV-C" or "400".', regex='^([A-Za-z]+-[A-Za-z]+)|(\\d+)$')])),
                ('upload_reg_text', models.BooleanField(default=True, help_text='Should the eCFR parser upload regulation text to eRegs?')),
                ('upload_locations', models.BooleanField(default=True, help_text='Should the parser process and upload section and subpart names for use in resource management?')),
                ('upload_fr_docs', models.BooleanField(default=True, help_text='Should the FR parser upload Federal Register Documents to eRegs?')),
                ('parser_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='parsers.parserconfiguration')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
            },
        ),
        migrations.CreateModel(
            name='ECFRParserResult',
            fields=[
                ('abstractparserresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parsers.abstractparserresult')),
                ('totalVersions', models.IntegerField()),
                ('skippedVersions', models.IntegerField()),
                ('errors', models.IntegerField()),
            ],
            bases=('parsers.abstractparserresult',),
        ),
    ]
