# Generated by Django 6.0.3 on 2026-08-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_move_parser_data_from_regcore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecfrparserresult',
            options={'verbose_name': 'eCFR Parser Result', 'verbose_name_plural': 'eCFR Parser Results'},
        ),
        migrations.AlterModelOptions(
            name='frparserresult',
            options={'verbose_name': 'Federal Register Parser Result', 'verbose_name_plural': 'Federal Register Parser Results'},
        ),
        migrations.RenameIndex(
            model_name='ecfrparserresult',
            new_name='parsers_ecf_title_1522aa_idx',
            old_name='parsers_ecf_title_part_idx',
        ),
        migrations.RenameIndex(
            model_name='ecfrparserresult',
            new_name='parsers_ecf_title_657d5a_idx',
            old_name='parsers_ecf_title_idx',
        ),
        migrations.RenameIndex(
            model_name='frparserresult',
            new_name='parsers_frp_documen_ff27ab_idx',
            old_name='parsers_fr_doc_idx',
        ),
        migrations.RemoveField(
            model_name='parserconfiguration',
            name='log_parse_errors',
        ),
        migrations.RemoveField(
            model_name='parserconfiguration',
            name='retries',
        ),
        migrations.RemoveField(
            model_name='parserconfiguration',
            name='skip_reg_versions',
        ),
        migrations.RemoveField(
            model_name='parserconfiguration',
            name='workers',
        ),
        migrations.AddField(
            model_name='parserconfiguration',
            name='skip_parsed_regs',
            field=models.BooleanField(default=True, help_text='Should the eCFR parser skip processing regulation parts that have been previously processed?'),
        ),
    ]
