# Generated by Django 6.0.3 on 2026-08-31 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0005_populate_initial_results'),
    ]

    operations = [
        migrations.CreateModel(
            name="FrLauncherResult",
            fields=[
                (
                    "abstractparserresult_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="parsers.abstractparserresult",
                    ),
                ),
                ("queued_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Federal Register Launcher Result",
                "verbose_name_plural": "Federal Register Launcher Results",
            },
            bases=("parsers.abstractparserresult",),
        ),
    ]
