# Generated by Django 6.0.3 on 2026-08-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0006_frlauncherresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractparserresult',
            name='log',
            field=models.TextField(blank=True),
        ),
    ]
