service: cmcs-eregs-site
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  iam:
    role: LambdaFunctionRole
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"
      - "application/pdf"
  logs:
    restApi:
      level: INFO
      roleManagedExternally: true
  lambdaHashingVersion: '20201221'
  tracing:
    apiGateway: true
  vpc:
    securityGroupIds:
      - ${self:custom.settings.security_group_ids.${self:custom.environment}}
    subnetIds:
      - ${ssm:/account_vars/vpc/subnets/private/a/id}
      - ${ssm:/account_vars/vpc/subnets/private/b/id}
  deploymentBucket:
      blockPublicAccess: true
  environment:
    DB_NAME: ${self:custom.settings.db_name.${self:custom.environment}}
    DB_USER: ${self:custom.settings.db_user}
    DB_PASSWORD: ${ssm:/eregulations/db/password}
    DB_HOST: ${self:custom.settings.db_host.${self:custom.environment}}
    DB_PORT: ${ssm:/eregulations/db/port}
    HTTP_AUTH_USER: ${ssm:/eregulations/http/user}
    HTTP_AUTH_PASSWORD: ${ssm:/eregulations/http/password}
    DJANGO_USERNAME: ${ssm:/eregulations/http/reader_user}
    DJANGO_PASSWORD: ${ssm:/eregulations/http/reader_password}
    DJANGO_ADMIN_USERNAME: ${ssm:/eregulations/http/user}
    DJANGO_ADMIN_PASSWORD: ${ssm:/eregulations/http/password}
    DJANGO_SETTINGS_MODULE: ${ssm:/eregulations/django_settings_module}
    ALLOWED_HOST: ${self:custom.settings.allowed_host}
    BASE_URL: ${ssm:/eregulations/base_url}
    STATIC_URL: ${self:custom.settings.static_url}
    CUSTOM_URL: ${ssm:/eregulations/custom_url, ''}
    SURVEY_URL: ${ssm:/eregulations/survey_url}
    SIGNUP_URL: ${ssm:/eregulations/signup_url}
    STAGE_ENV: ${self:custom.stage}
    SEARCHGOV_KEY: ${ssm:/eregulations/searchgov/key}
    SEARCHGOV_SITE_NAME: ${ssm:/eregulations/searchgov/site_name}
    AWS_STORAGE_BUCKET_NAME: file-repo-eregs-${self:custom.stage}
    OIDC_OP_JWKS_ENDPOINT: ${ssm:/eregulations/oidc/jwks_endpoint}
    OIDC_RP_CLIENT_ID: ${ssm:/eregulations/oidc/client_id}
    OIDC_RP_CLIENT_SECRET: ${ssm:/eregulations/oidc/client_secret}
    OIDC_OP_AUTHORIZATION_ENDPOINT: ${ssm:/eregulations/oidc/authorization_endpoint}
    OIDC_OP_TOKEN_ENDPOINT: ${ssm:/eregulations/oidc/token_endpoint}
    OIDC_OP_USER_ENDPOINT: ${ssm:/eregulations/oidc/user_endpoint}
    OIDC_END_EUA_SESSION: ${ssm:/eregulations/oidc/end_eua_session}
    DEPLOY_NUMBER: ${self:custom.settings.deploy_number.${self:custom.environment}}
    EUA_FEATUREFLAG: ${ssm:/eregulations/eua/featureflag}
    BASIC_SEARCH_FILTER: ${ssm:/eregulations/basic_search_filter}
    QUOTED_SEARCH_FILTER: ${ssm:/eregulations/quoted_search_filter}
    TEXT_EXTRACTOR_ARN: ${self:custom.settings.text_extractor_arn}
    GA_ID: ${ssm:/eregulations/http/google_analytics}

package:
  individually: false
  exclude:
    - node_modules/**
    - nginx/**

custom:
  environment: ${env:ENVIRONMENT}
  localstack:
    stages:
      - local
  stage: ${opt:stage, self:provider.stage}
  wsgi:
    app: handler.application
    packRequirements: false
  settings:
    db_name:
      local: eregs
      experimental: ${self:custom.stage}
      deploy: eregs
    db_user: eregsuser
    static_url: ${cf:cmcs-eregs-static-assets-${self:custom.stage}.StaticURL}/
    #text_extractor_arn: ${cf:text-extractor-${self:custom.stage}.TextDashextractorLambdaFunctionQualifiedArn}
    text_extractor_arn: ""
    deploy_number:
      local: ${sls:instanceId}
      experimental: ${env:RUN_ID, ""}
      deploy: ${env:RUN_ID, ""}
    allowed_host: ".amazonaws.com"
    security_group_ids:
      local: !Ref ServerlessSecurityGroup
      experimental: ${ssm:/eregulations/aws/securitygroupid}
      deploy: !Ref ServerlessSecurityGroup
    db_host:
      local:
        Fn::GetAtt: [ RDSResource15, Endpoint.Address ]
      experimental: ${ssm:/eregulations/db/host}
      deploy: ${ssm:/eregulations/db/host}
  cloudfrontInvalidate:
    - distributionId: ${cf:cmcs-eregs-static-assets-${self:custom.stage}.CloudFrontDistributionId}
      items:
        - "/*"
  associateWaf:
    name: APIGateway-eregs-allow-usa-plus-territories-${self:custom.stage}
    version: V2

## CAN FUNCTIONS BE SIMPLIFIED?
functions: ${file(serverless_functions/${self:custom.environment}_functions.yml)}

resources:
  Conditions:
    IsDeploy: !Equals ["deploy", "${self:custom.environment}"]

  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: file-repo-eregs-${self:custom.stage}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - HEAD
              MaxAge: 3000

    WAFRegionalWebACL: ${file(aws_resources/waf.yml):WAFRegionalWebACL}

    LambdaFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        Path: ${ssm:/account_vars/iam/path}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        # note that these rights are needed if you want your function to be able to communicate with resources within your vpc
        PermissionsBoundary:
          Fn::Join:
            - ''
            - - 'arn:aws:iam::'
              - Ref: AWS::AccountId
              - ':policy'
              - ${ssm:/account_vars/iam/permissions_boundary_policy}
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        Policies:
          - PolicyName: StorageBucketPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Deny
                  Action: "*"
                  Condition:
                    Bool:
                      "aws:SecureTransport": false
                  Resource:
                    - Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - "Ref" : "ServerlessDeploymentBucket"
                    - "arn:aws:s3:::file-repo-eregs-${self:custom.stage}/*"
          - PolicyName: LambdaPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                -  Effect: "Allow"
                   Action:
                     - "s3:PutObject"
                     - "s3:GetObject"
                     - "s3:DeleteObject"
                     - "s3:ListBucket"
                   Resource:
                     - Fn::Join:
                       - ""
                       - - "arn:aws:s3:::"
                         - "Ref" : "ServerlessDeploymentBucket"
                     - "arn:aws:s3:::file-repo-eregs-${self:custom.stage}"
                     - "arn:aws:s3:::file-repo-eregs-${self:custom.stage}/*"
                -  Effect: "Allow"
                   Action:
                     - "lambda:InvokeFunction"
                   Resource:
                     - "${self:custom.settings.text_extractor_arn}" # Extractor created by the environment

    ServerlessSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Condition: IsDeploy
      Properties:
        GroupDescription: SecurityGroup for Serverless Functions
        VpcId: ${ssm:/account_vars/vpc/id}
        Tags:
          - Key: "Name"
            Value: "ServerlessSecurityGroup"

    DBSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Condition: IsDeploy
      Properties:
        GroupDescription: SecurityGroup for Database
        VpcId: ${ssm:/account_vars/vpc/id}
        Tags:
          - Key: "Name"
            Value: "DBSecurityGroup"

    DBSecurityGroupIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Condition: IsDeploy
      Properties:
        GroupId: !Ref 'DBSecurityGroup'
        IpProtocol: tcp
        FromPort: ${ssm:/eregulations/db/port}
        ToPort: ${ssm:/eregulations/db/port}
        SourceSecurityGroupId: !Ref 'ServerlessSecurityGroup'

    DBSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Condition: IsDeploy
      Properties:
        DBSubnetGroupDescription: "RDS Subnet Group"
        SubnetIds:
          - ${ssm:/account_vars/vpc/subnets/private/a/id}
          - ${ssm:/account_vars/vpc/subnets/private/b/id}
        Tags:
          - Key: "Name"
            Value: "DBSubnetGroup"

    AuroraRDSClusterParameter15:
      Type: AWS::RDS::DBClusterParameterGroup
      Condition: IsDeploy
      Properties:
        Description: Parameter group for the Serverless Aurora RDS DB.
        Family: aurora-postgresql15
        Parameters:
          rds.force_ssl: 1

    AuroraRDSInstanceParameter15:
      Type: AWS::RDS::DBParameterGroup
      Condition: IsDeploy
      Properties:
        Description: Parameter group for the Serverless Aurora RDS DB.
        Family: aurora-postgresql15
        Parameters:
          shared_preload_libraries: auto_explain,pg_stat_statements,pg_hint_plan,pgaudit
          log_statement: "ddl"
          log_connections: 1
          log_disconnections: 1
          log_lock_waits: 1
          log_min_duration_statement: 5000
          auto_explain.log_min_duration: 5000
          auto_explain.log_verbose: 1
          log_rotation_age: 1440
          log_rotation_size: 102400
          rds.log_retention_period: 10080
          random_page_cost: 1
          track_activity_query_size: 16384
          idle_in_transaction_session_timeout: 7200000
          statement_timeout: 7200000
          search_path: '"$user",public'
          pgaudit.role: "rds_pgaudit"
          pgaudit.log: "ALL"

    RDSResource15:
      Type: AWS::RDS::DBCluster
      Condition: IsDeploy
      DeletionPolicy: Retain
      Properties:
        MasterUsername: ${self:custom.settings.db_user}
        StorageEncrypted: true
        MasterUserPassword: ${ssm:/eregulations/db/password}
        DBSubnetGroupName:
          Ref: DBSubnetGroup
        Engine: aurora-postgresql
        EngineVersion: "15.2"
        DatabaseName: 'eregs'
        BackupRetentionPeriod: 7
        DBClusterParameterGroupName:
          Ref: AuroraRDSClusterParameter15
        VpcSecurityGroupIds:
          - !Ref 'DBSecurityGroup'

    AuroraRDSInstance15:
      Type: AWS::RDS::DBInstance
      Condition: IsDeploy
      DeletionPolicy: Retain
      Properties:
        DBInstanceClass: db.r6g.large
        StorageEncrypted: true
        Engine: aurora-postgresql
        EngineVersion: "15.2"
        PubliclyAccessible: false
        DBParameterGroupName:
          Ref: AuroraRDSInstanceParameter15
        DBClusterIdentifier:
          Ref: RDSResource15

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-go-plugin
  - serverless-cloudfront-invalidate
  - serverless-associate-waf
  - serverless-localstack
