# Generated by Django 3.2.21 on 2023-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileindex',
            name='file_name_string',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='fileindex',
            name='doc_name_string',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='fileindex',
            name='doc_type_string',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='fileindex',
            name='subject_string',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='fileindex',
            name='summary_string',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
