# Generated by Django 3.2.21 on 2023-09-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_search', '0002_auto_20230929_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileindex',
            name='date_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
