# CloudFormation Resources
# Create WAF Regional Web ACL with Rate-Based Rule to Prevent HTTP Flood DDoS Attack
WAFRegionalWebACL:
  Type: "AWS::WAFv2::WebACL"
  Properties:
    Name: ${self:custom.stage}-cmcs-eregs-ApiGwWebACL
    Scope: REGIONAL
    Description: WAF Regional Web ACL
    DefaultAction:
      Block: {}
    Rules:
        Name: bf-test-admin-allow-usa-plus-territories
        Priority: 0
        Statement:
          GeoMatchStatement:
            CountryCodes:
              - GU
              - PR
              - US
              - UM
              - VI
              - MP
              - AS
        Action:
          Allow: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName: HTTP-Flood-Prevent-Rule-Metric
    VisibilityConfig:
      SampledRequestsEnabled: true
      CloudWatchMetricsEnabled: true
      MetricName: "WafWebAcl"

