WAFRegionalWebACL:
  Type: "AWS::WAFv2::WebACL"
  Properties:
    Name: APIGateway-eregs-allow-usa-plus-territories-${self:custom.stage}
    Scope: REGIONAL
    Description: WAF Regional Web ACL
    DefaultAction:
      Block: {}
    VisibilityConfig:
      SampledRequestsEnabled: true
      CloudWatchMetricsEnabled: true
      MetricName: ApiGateway-eregs-allow-usa-plus-territories

    Rules:
      - Name: eregs-allow-usa-plus-territories-rule
        Priority: 0
        Statement:
          GeoMatchStatement:
            CountryCodes:
              - GU
              - PR
              - US
              - UM
              - VI
              - MP
              - AS
        Action:
          Allow: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName: eregs-allow-usa-plus-territories-metric
