# CloudFormation Resources
# Create WAF Regional Web ACL with Rate-Based Rule to Prevent HTTP Flood DDoS Attack
WAFRegionalWebACL:
  Type: "AWS::WAFv2::WebACL"
  Properties:
    Name: ${self:custom.stage}-cmcs-eregs-waf
    Scope: REGIONAL
    Description: WAF Regional Web ACL
    DefaultAction:
      Allow: {}
    VisibilityConfig:
      SampledRequestsEnabled: true
      CloudWatchMetricsEnabled: true
