# Generated by Django 3.2.5 on 2021-07-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('document', models.JSONField()),
                ('structure', models.JSONField()),
            ],
            options={
                'unique_together': {('name', 'title', 'date')},
            },
        ),
    ]
