# Generated by Django 3.2.11 on 2022-01-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workers', models.IntegerField(default=3, help_text='The number of worker threads used to parse regulations.')),
                ('attempts', models.IntegerField(default=3, help_text='Number of times to retry parsing if it fails to complete.')),
                ('loglevel', models.CharField(choices=[('warn', 'Warning'), ('error', 'Error'), ('fatal', 'Fatal'), ('info', 'Info'), ('debug', 'Debug'), ('trace', 'Trace')], default='info', help_text="Specifies the level of detail contained in the parser's logs.", max_length=5)),
            ],
            options={
                'verbose_name': 'Parser Configuration',
            },
        ),
        migrations.CreateModel(
            name='TitleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(help_text='The title of the regulations to parse, e.g. 42.', unique=True)),
                ('subchapters', models.TextField(blank=True, help_text='A comma-separated list of subchapters to parse. All parts within the listed subchapters will be included. E.g., "IV-C, IV-D, IV-F" or simply "IV-C".')),
                ('parts', models.TextField(blank=True, help_text='A comma-separated list of individual parts to parse if you do not wish to include the entire subchapter. E.g., "400, 457, 460".')),
                ('parser_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='regcore.parserconfiguration')),
            ],
        ),
    ]
