# Generated by Django 3.2.5 on 2021-07-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchindex',
            name='search_vector',
        ),
    ]
