# Generated by Django 3.2.12 on 2022-04-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_searchindex_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('baseWord', models.CharField(max_length=32)),
                ('synonyms', models.ManyToManyField(related_name='_search_synonym_synonyms_+', to='search.Synonym')),
            ],
        ),
    ]
