# Generated by Django 3.2.12 on 2022-04-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_synonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='_search_synonym_synonyms_+', to='search.Synonym'),
        ),
    ]
