# Generated by Django 3.2.18 on 2023-03-17 13:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_synonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchindex',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='search_sear_vector__03cfcb_gin'),
        ),
    ]
