# Generated by Django 3.2.16 on 2022-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_synonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConfigruration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
            ],
        ),
    ]
