# Generated by Django 3.2.18 on 2023-03-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0013_alter_part_options'),
        ('search', '0003_synonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndexV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=32)),
                ('section_number', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('section_string', models.CharField(max_length=32)),
                ('section_title', models.TextField(null=True)),
                ('part_title', models.TextField(null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regcore.part')),
            ],
        ),
    ]
