# Generated by Django 3.2.16 on 2022-12-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_searchconfigruration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchConfigruration',
            new_name='SearchConfiguration',
        ),
    ]
