# Generated by Django 3.2.12 on 2022-04-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_synonym_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='baseWord',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
