# Generated by Django 3.2.18 on 2023-03-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_searchiindexv2vector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchIndex',
        ),
    ]
