# Generated by Django 5.0.4 on 2024-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_alter_searchquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='synonyms',
            field=models.ManyToManyField(blank=True, to='search.synonym'),
        ),
    ]
