# Generated by Django 3.2.12 on 2022-04-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0004_part_depth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('title', models.IntegerField()),
                ('subchapters', models.TextField(blank=True)),
                ('parts', models.TextField(blank=True)),
                ('workers', models.IntegerField()),
                ('attempts', models.IntegerField()),
            ],
        ),
    ]
