# Generated by Django 3.2.13 on 2022-08-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0005_abstractparserresult_ecfrparserresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractparserresult',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='parserconfiguration',
            name='attempts',
        ),
    ]
