# Generated by Django 3.2.13 on 2022-06-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0005_abstractparserresult_ecfrparserresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_indexing', models.BooleanField(default=False, help_text='Should robots be allowed to index this website?')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
