# Generated by Django 3.2.13 on 2022-09-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0006_auto_20220826_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='depth_stack',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
