# Generated by Django 3.2.13 on 2022-09-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0007_part_depth_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='title_object',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
