# Generated by Django 3.2.13 on 2022-09-13 11:38

from django.db import migrations, models


def convert_name_and_title(apps, schema_editor):
    Part = apps.get_model("regcore", "Part")
    for i in Part.objects.all():
        try:
            i.title_temp = int(i.title)
            i.name_temp = int(i.name)
            i.save()
        except:
            i.delete() # will be recreated on next parser run


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0008_auto_20220912_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='name_temp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='title_temp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(convert_name_and_title),
        migrations.RemoveField(
            model_name='part',
            name='title',
        ),
        migrations.RemoveField(
            model_name='part',
            name='name',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='name_temp',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='title_temp',
            new_name='title',
        ),
    ]
