# Generated by Django 3.2.13 on 2022-09-13 18:05

from django.db import migrations


def generate_depth_stacks(apps, schema_editor):
    Part = apps.get_model("regcore", "Part")
    for part in Part.objects.all():
        # create depth stack for front page TOC
        stack = []
        current = part.structure
        for i in range(part.depth + 1):
            structure_copy = current.copy()
            del structure_copy["children"]
            stack.append(structure_copy)
            current = current["children"][0]
        part.depth_stack = stack
        part.save()


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0009_auto_20220913_1138'),
    ]

    operations = [
        migrations.RunPython(generate_depth_stacks),
    ]
