# Generated by Django 3.2.13 on 2022-09-14 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0010_auto_20220913_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserconfiguration',
            name='retries',
            field=models.IntegerField(default=3, help_text='The number of times to retry parsing a part version before moving on if it fails.', validators=[django.core.validators.MinValueValidator(limit_value=0, message='The number of retries must be at least 0!')]),
        ),
    ]
