# Generated by Django 3.2.13 on 2022-09-23 11:56

from django.db import migrations, models
import django


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0011_parserconfiguration_retries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parserconfiguration',
            name='skip_versions',
        ),
        migrations.AddField(
            model_name='parserconfiguration',
            name='skip_fr_documents',
            field=models.BooleanField(default=True, help_text='Should the Federal Register parser skip processing documents that have been previously processed?'),
        ),
        migrations.AddField(
            model_name='parserconfiguration',
            name='skip_reg_versions',
            field=models.BooleanField(default=True, help_text='Should the eCFR parser skip processing versions of regulation parts that have been previously processed?'),
        ),
        migrations.AlterField(
            model_name='parserconfiguration',
            name='log_parse_errors',
            field=models.BooleanField(default=False, help_text='Should the eCFR parser log errors encountered while processing the raw XML data from eCFR?'),
        ),
        migrations.AlterField(
            model_name='parserconfiguration',
            name='retries',
            field=models.IntegerField(default=3, help_text='The number of times to retry parsing before moving on if it fails.', validators=[django.core.validators.MinValueValidator(limit_value=0, message='The number of retries must be at least 0!')]),
        ),
        migrations.AlterField(
            model_name='parserconfiguration',
            name='upload_supplemental_locations',
            field=models.BooleanField(default=True, help_text='Should the eCFR parser process and upload section and subpart names for use in supplemental content management?'),
        ),
        migrations.AlterField(
            model_name='parserconfiguration',
            name='workers',
            field=models.IntegerField(default=3, help_text='The number of worker threads used to parse simultaneously.', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Number of workers must be at least 1!')]),
        ),
    ]
