# Generated by Django 3.2.18 on 2023-03-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0012_auto_20220923_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('title', 'name', '-date')},
        ),
    ]
