# Generated by Django 6.0.3 on 2026-09-08 16:22

from django.db import migrations


DROP_OLD_UNIQUE_SQL = """
DO $$
DECLARE
    old_constraint_name text;
BEGIN
    SELECT c.conname
      INTO old_constraint_name
      FROM pg_constraint c
      JOIN pg_class t ON t.oid = c.conrelid
      JOIN pg_namespace n ON n.oid = t.relnamespace
      JOIN pg_attribute a1 ON a1.attrelid = t.oid AND a1.attnum = c.conkey[1]
      JOIN pg_attribute a2 ON a2.attrelid = t.oid AND a2.attnum = c.conkey[2]
      JOIN pg_attribute a3 ON a3.attrelid = t.oid AND a3.attnum = c.conkey[3]
     WHERE c.contype = 'u'
       AND t.relname = 'regcore_part'
       AND n.nspname = current_schema()
       AND array_length(c.conkey, 1) = 3
       AND a1.attname = 'name'
       AND a2.attname = 'title'
       AND a3.attname = 'date'
     LIMIT 1;

    IF old_constraint_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE regcore_part DROP CONSTRAINT %I', old_constraint_name);
    END IF;
END $$;
"""


ADD_NEW_UNIQUE_SQL = """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint c
          JOIN pg_class t ON t.oid = c.conrelid
          JOIN pg_namespace n ON n.oid = t.relnamespace
          JOIN pg_attribute a1 ON a1.attrelid = t.oid AND a1.attnum = c.conkey[1]
          JOIN pg_attribute a2 ON a2.attrelid = t.oid AND a2.attnum = c.conkey[2]
         WHERE c.contype = 'u'
           AND t.relname = 'regcore_part'
           AND n.nspname = current_schema()
           AND array_length(c.conkey, 1) = 2
           AND a1.attname = 'title'
           AND a2.attname = 'name'
    ) THEN
        ALTER TABLE regcore_part
        ADD CONSTRAINT regcore_part_title_name_uniq UNIQUE (title, name);
    END IF;
END $$;
"""


DROP_NEW_UNIQUE_SQL = """
ALTER TABLE regcore_part DROP CONSTRAINT IF EXISTS regcore_part_title_name_uniq;
"""


ADD_OLD_UNIQUE_SQL = """
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint c
          JOIN pg_class t ON t.oid = c.conrelid
          JOIN pg_namespace n ON n.oid = t.relnamespace
          JOIN pg_attribute a1 ON a1.attrelid = t.oid AND a1.attnum = c.conkey[1]
          JOIN pg_attribute a2 ON a2.attrelid = t.oid AND a2.attnum = c.conkey[2]
          JOIN pg_attribute a3 ON a3.attrelid = t.oid AND a3.attnum = c.conkey[3]
         WHERE c.contype = 'u'
           AND t.relname = 'regcore_part'
           AND n.nspname = current_schema()
           AND array_length(c.conkey, 1) = 3
           AND a1.attname = 'name'
           AND a2.attname = 'title'
           AND a3.attname = 'date'
    ) THEN
        ALTER TABLE regcore_part
        ADD CONSTRAINT regcore_part_name_title_date_uniq UNIQUE (name, title, date);
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0016_remove_versions'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"{DROP_OLD_UNIQUE_SQL}\n{ADD_NEW_UNIQUE_SQL}",
                    reverse_sql=f"{DROP_NEW_UNIQUE_SQL}\n{ADD_OLD_UNIQUE_SQL}",
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='part',
                    unique_together={('title', 'name')},
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('title', 'name')},
        ),
    ]
