# Generated by Django 6.0.3 on 2026-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0016_remove_versions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('title', 'name')},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    DECLARE
                        old_constraint RECORD;
                    BEGIN
                        FOR old_constraint IN
                            SELECT c.conname
                            FROM pg_constraint c
                            JOIN pg_class t ON t.oid = c.conrelid
                            WHERE t.relname = 'regcore_part'
                                AND c.contype = 'u'
                                AND array_length(c.conkey, 1) = 3
                                AND EXISTS (
                                    SELECT 1
                                    FROM pg_attribute a
                                    WHERE a.attrelid = t.oid
                                        AND a.attname = 'name'
                                        AND a.attnum = ANY (c.conkey)
                                )
                                AND EXISTS (
                                    SELECT 1
                                    FROM pg_attribute a
                                    WHERE a.attrelid = t.oid
                                        AND a.attname = 'title'
                                        AND a.attnum = ANY (c.conkey)
                                )
                                AND EXISTS (
                                    SELECT 1
                                    FROM pg_attribute a
                                    WHERE a.attrelid = t.oid
                                        AND a.attname = 'date'
                                        AND a.attnum = ANY (c.conkey)
                                )
                        LOOP
                            EXECUTE format('ALTER TABLE regcore_part DROP CONSTRAINT %I', old_constraint.conname);
                        END LOOP;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint c
                            JOIN pg_class t ON t.oid = c.conrelid
                            WHERE t.relname = 'regcore_part'
                                AND c.contype = 'u'
                                AND array_length(c.conkey, 1) = 3
                                AND EXISTS (
                                    SELECT 1
                                    FROM pg_attribute a
                                    WHERE a.attrelid = t.oid
                                        AND a.attname = 'name'
                                        AND a.attnum = ANY (c.conkey)
                                )
                                AND EXISTS (
                                    SELECT 1
                                    FROM pg_attribute a
                                    WHERE a.attrelid = t.oid
                                        AND a.attname = 'title'
                                        AND a.attnum = ANY (c.conkey)
                                )
                                AND EXISTS (
                                    SELECT 1
                                    FROM pg_attribute a
                                    WHERE a.attrelid = t.oid
                                        AND a.attname = 'date'
                                        AND a.attnum = ANY (c.conkey)
                                )
                        ) THEN
                            ALTER TABLE regcore_part
                            ADD CONSTRAINT regcore_part_name_title_date_uniq UNIQUE (name, title, date);
                        END IF;
                    END
                    $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='part',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(
                fields=('title', 'name'),
                name='regcore_part_title_name_unique',
            ),
        ),
    ]
