name: Deploy CDK (Manager)

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy-matrix:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        environment: ["dev", "val"]
    uses: ./.github/workflows/deploy-cdk.yml
    with:
      environment: ${{ matrix.environment }}
    secrets: inherit
