name: "ESLint"

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-eslint:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      # Setup node environment
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # Execute linting
      - name: Run ESLint on front end
        if: success()
        working-directory: ./solution
        run: |
          make eslint-frontend
      - name: Run ESLint on CDK TS files
        # if: success()
        if: false # Disable CDK linting for now
        working-directory: ./solution
        run: |
          make eslint-cdk
