name: Lint Python Code

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ruff:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: chartboost/ruff-action@v1
        with:
          src: "./solution"
          args: "check --preview"
