name: Lint Python Code

on: [ push, pull_request, workflow_dispatch ]

jobs:
  lint-python:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      # Install uv
      - name: Install uv
        run: |
          python -m pip install --upgrade pip uv

      # Lint the backend Python code
      - name: Lint backend code
        run: |
          pushd solution/backend
          uv sync --locked --no-install-project
          uv run ruff check --preview .
          popd

      # Lint the text-extractor Python code
      - name: Lint text-extractor code
        run: |
          pushd solution/text-extractor
          uv sync --locked --no-install-project
          uv run ruff check --preview .
          popd

      # Lint the parser Python code
      - name: Lint parser code
        run: |
          pushd solution/parsers
          uv sync --locked --no-install-project
          uv run --with ruff ruff check --preview .
          popd

      # Lint the MCP server Python code
      - name: Lint mcp-server code
        run: |
          pushd solution/mcp-server
          uv sync --locked --no-install-project
          uv run --with ruff ruff check --preview .
          popd

      # Lint the lambda-proxy Python code
      - name: Lint lambda-proxy code
        run: |
          pushd solution/lambda-proxy
          uv run --with ruff ruff check --preview .
          popd
