name: Load Supplementary Content

on: 
  workflow_dispatch:

jobs:
  load:
    environment:
      name: 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: get branch name
        run: |
          lower_case=${GITHUB_REF,,}
          echo "branch_name=${lower_case#refs/heads/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          submodules: false
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16' # The Go version to download (if necessary) and use.
      - run: make supplementary_content
      - name: add supplementary content to database
        run: |
          pushd serverless
          npm install serverless -g
          npm install
          serverless invoke --function populate_content --stage ${{ github.event.inputs.env }}-$branch_name
          popd
