name: Reusable Test Child

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_OIDC_ROLE_TO_ASSUME:
        required: true
        description: 'AWS OIDC role to assume for deployment'
      AWS_ACCOUNT_ID:
        required: true
        description: 'AWS account ID for deployment'

permissions:
  id-token: write
  contents: read
  actions: read


jobs:
  do-thing-a:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws_default_region }}

      - name: Do thing A
        run: echo "Doing thing A in environment ${{ inputs.environment }}"

  do-thing-b:
    needs: do-thing-a
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws_default_region }}

      - name: Do thing B
        run: echo "Doing thing B in environment ${{ inputs.environment }}"
