name: Unit Test Text Extractor Code

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test-text-extractor:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Install Python dependencies
      - name: Install Python dependencies
        if: success()
        run: |
          python -m pip install --upgrade pip
          pip install -r ./solution/backend/requirements.txt
          
      # Execute the Python tests
      - name: Run Python unit tests
        if: success()
        working-directory: ./solution/text-extractor
        run: |
          pytest -vv
