name: Test (Matrix Job)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  actions: read

jobs:  
  do-thing-one:
    name: 1. Do a thing
    runs-on: ubuntu-22.04    
    environment:      
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true     
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Do nothing else
        id: do-nothing
        run: |
          pushd cdk-eregs
          echo Hello
          popd

  do-thing-two:
    needs: do-thing-one
    name: 2. Do another thing
    runs-on: ubuntu-22.04
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true     
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Asdf
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          CDK_DEBUG: true
        run: |
          pushd cdk-eregs
          echo Something else
          popd
