name: Unit Test Parsers

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "solution/parsers/**"
      - "solution/backend/parsers/**"
      - "cdk-eregs/lib/stacks/*parser*"
  push:
    branches:
      - main

permissions:
  contents: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test-parsers:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install parser test dependencies
        run: |
          python -m pip install --upgrade pip uv
          pushd solution/parsers
          uv sync --locked
          popd

      - name: Run parser unit tests
        run: |
          pushd solution
          make parsers.test
          popd
