name: Test (Manager)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read
  actions: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy-matrix:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        environment: ["dev", "val"]
    uses: ./.github/workflows/test.yml
    with:
      environment: ${{ matrix.environment }}
    secrets: inherit
